import type { Localized } from "@/i18n/localized";

/**
 * Page copy for the Effects library, kept apart from the effect data so
 * client components can import it without bundling every effect’s text.
 */
export const effectsCopy = {
  eyebrow: { th: "คลังเอฟเฟกต์ · {n} แบบ", en: "Effects library · {n} effects", zh: "特效库 · {n} 种", ja: "エフェクト集 · {n} 種類" },
  title: {
    th: ["ขยับเมาส์", "แล้วรู้สึกถึง UX"],
    en: ["Move your mouse.", "Feel the UX."],
    zh: ["动动鼠标，", "感受 UX。"],
    ja: ["マウスを動かして、", "UX を感じよう。"],
  } as Localized<string[]>,
  metaTitle: { th: "คลังเอฟเฟกต์", en: "Effects library", zh: "交互特效库", ja: "エフェクト集" },
  lead: {
    th: "เอฟเฟกต์ที่เล่นได้จริงทุกชิ้น พร้อมเหตุผลว่าทำไมถึงได้ผล และ Prompt ให้ก๊อปไปสร้างเองใน AI coding tool",
    en: "Every effect here is live. Each one explains why it works and comes with a prompt you can paste into an AI coding tool to build it yourself.",
    zh: "这里的每个特效都能直接玩。每一个都解释了为什么有效，并附上提示词，可以粘贴到 AI 编程工具里自己做出来。",
    ja: "ここにあるエフェクトはすべて実際に触れます。なぜ効くのかの説明と、AI コーディングツールに貼り付けて自分で作れるプロンプト付き。",
  },
  startCta: { th: "เริ่มเล่นเลย", en: "Start playing", zh: "开始玩", ja: "さっそく遊ぶ" },
  formulaCta: { th: "สูตรเขียน Prompt", en: "The prompt formula", zh: "提示词公式", ja: "プロンプトの公式" },
  galleryTitle: { th: "เอฟเฟกต์ทั้งหมด", en: "All effects", zh: "全部特效", ja: "すべてのエフェクト" },
  filterLabel: { th: "หมวด", en: "Category", zh: "分类", ja: "カテゴリー" },
  all: { th: "ทั้งหมด", en: "All", zh: "全部", ja: "すべて" },
  showing: { th: "แสดง {n} จาก {total}", en: "Showing {n} of {total}", zh: "显示 {n} / {total}", ja: "{total} 件中 {n} 件を表示" },
  motionLabel: { th: "เล่นเอฟเฟกต์", en: "Play effects", zh: "播放特效", ja: "エフェクトを再生" },
  motionReduced: {
    th: "อุปกรณ์ของคุณตั้งค่าลดการเคลื่อนไหวไว้ เอฟเฟกต์จึงหยุดรอก่อน เปิดเล่นเองได้ทุกเมื่อ",
    en: "Your device asks for less motion, so effects start paused. You can play them anytime.",
    zh: "你的设备设置了减少动态效果，所以特效默认暂停。你可以随时打开。",
    ja: "端末で「視差効果を減らす」が設定されているため、エフェクトは一時停止中です。いつでも再生できます。",
  },
  motionOn: {
    th: "เอฟเฟกต์ทำงานอยู่ ปิดได้ถ้าการเคลื่อนไหวรบกวนคุณ",
    en: "Effects are playing. Turn them off if motion bothers you.",
    zh: "特效正在播放。如果动态效果让你不适，可以关闭。",
    ja: "エフェクト再生中。動きが気になる場合はオフにできます。",
  },
  paused: { th: "หยุดไว้", en: "Paused", zh: "已暂停", ja: "一時停止中" },
  playOne: { th: "เปิดเอฟเฟกต์", en: "Play effects", zh: "播放特效", ja: "再生する" },
  stackLabel: { th: "Prompt สำหรับ", en: "Prompts for", zh: "提示词适用于", ja: "プロンプトの対象" },
  copyPrompt: { th: "ก๊อป Prompt", en: "Copy prompt", zh: "复制提示词", ja: "プロンプトをコピー" },
  copied: {
    th: "ก๊อปแล้ว วางใน AI coding tool ได้เลย",
    en: "Copied — paste it into your AI coding tool",
    zh: "已复制，粘贴到你的 AI 编程工具即可",
    ja: "コピーしました。AI コーディングツールに貼り付けてください",
  },
  copyFailed: { th: "ก๊อปไม่ได้ ลองเลือกข้อความเอง", en: "Couldn’t copy — select the text instead", zh: "复制失败，请手动选择文字", ja: "コピーできませんでした。テキストを選択してください" },
  howToBuild: { th: "วิธีสร้าง", en: "How to build it", zh: "制作方法", ja: "作り方" },
  tried: { th: "ลองแล้ว", en: "Tried", zh: "已体验", ja: "体験済み" },
  stageHint: {
    th: "เดโม {name}: ใช้ปุ่มลูกศรเพื่อขยับ และ Enter เพื่อกด",
    en: "{name} demo: use the arrow keys to move and Enter to press",
    zh: "{name} 演示：用方向键移动，按 Enter 点击",
    ja: "{name} のデモ：矢印キーで移動、Enter で押す",
  },
  reset: { th: "เริ่มใหม่", en: "Restart", zh: "重新开始", ja: "やり直す" },
  levelLabel: { th: "ระดับ", en: "Level", zh: "难度", ja: "レベル" },
  builtWith: { th: "สร้างด้วย", en: "Built with", zh: "使用技术", ja: "使う技術" },
  why: { th: "ทำไมถึงได้ผล", en: "Why it works", zh: "为什么有效", ja: "なぜ効くのか" },
  use: { th: "ใช้เมื่อ", en: "Use it for", zh: "适合用于", ja: "使いどころ" },
  avoid: { th: "เลี่ยงเมื่อ", en: "Avoid it for", zh: "避免用于", ja: "避けたい場面" },
  promptTitle: { th: "สร้างด้วย AI", en: "Build it with AI", zh: "用 AI 来做", ja: "AI で作る" },
  promptLead: {
    th: "Prompt นี้เขียนตามสูตร 5 ส่วน ก๊อปไปวางใน AI coding tool ได้เลย แล้วลองปรับตัวเลขในส่วน Feel ให้เป็นสไตล์ของคุณ",
    en: "This prompt follows the five-part formula. Paste it into an AI coding tool, then tune the numbers in Feel to make it yours.",
    zh: "这个提示词遵循五段式公式。粘贴到 AI 编程工具后，调整 Feel 里的数值，让它成为你的风格。",
    ja: "このプロンプトは 5 つのパートの公式に沿っています。AI コーディングツールに貼り付けたら、Feel の数値を調整して自分らしく。",
  },
  promptEnglish: {
    th: "Prompt เป็นภาษาอังกฤษ เพราะ AI เขียนโค้ดได้แม่นที่สุดกับศัพท์เทคนิคภาษาอังกฤษ และเป็นคำเดียวกับที่ใช้ในที่ทำงาน",
    en: "",
    zh: "提示词使用英文，因为 AI 对英文技术术语的理解最准确，这也是工作中会用到的词。",
    ja: "プロンプトは英語です。AI は英語の技術用語を最も正確に理解し、仕事で使う言葉でもあるからです。",
  },
  related: { th: "แนวคิดเบื้องหลัง", en: "The ideas behind it", zh: "背后的概念", ja: "背景にある考え方" },
  allEffects: { th: "เอฟเฟกต์ทั้งหมด", en: "All effects", zh: "全部特效", ja: "すべてのエフェクト" },
  prev: { th: "ก่อนหน้า", en: "Previous", zh: "上一个", ja: "前へ" },
  next: { th: "ถัดไป", en: "Next", zh: "下一个", ja: "次へ" },
  englishNote: {
    th: "",
    en: "",
    zh: "本页的详细说明目前为英文。",
    ja: "このページの詳しい説明は現在英語です。",
  },
  formula: {
    title: { th: "สูตร Prompt 5 ส่วน", en: "The five-part prompt formula", zh: "五段式提示词公式", ja: "5 パートのプロンプト公式" },
    lead: {
      th: "AI สร้างเอฟเฟกต์ได้ในไม่กี่วินาที แต่ที่ทำให้ผลงานดูโปรคือการบอกให้ครบ 5 อย่างนี้ โดยเฉพาะข้อสุดท้ายที่คนส่วนใหญ่ลืม",
      en: "AI can build an effect in seconds. What makes the result look professional is telling it these five things — especially the last one, which most people forget.",
      zh: "AI 几秒钟就能做出特效。让成果显得专业的关键，是把这五件事说清楚——尤其是最后一项，大多数人都会忘记。",
      ja: "AI はエフェクトを数秒で作れます。仕上がりをプロらしくするのは、この 5 つを伝えること。特に最後のひとつは多くの人が忘れがちです。",
    },
    parts: [
      {
        key: "Effect",
        label: { th: "ภาพที่เห็น", en: "What people see", zh: "看到什么", ja: "何が見えるか" },
        desc: {
          th: "อะไรขยับ หน้าตาเป็นอย่างไร วาดภาพด้วยคำให้ชัด",
          en: "What moves and what it looks like. Paint the picture.",
          zh: "什么在动，看起来是什么样子。用文字把画面描绘出来。",
          ja: "何がどう動き、どう見えるか。言葉で絵を描きます。",
        },
        example: "the button drifts toward the cursor",
      },
      {
        key: "Trigger",
        label: { th: "อะไรทำให้เกิด", en: "What starts it", zh: "什么触发", ja: "何がきっかけか" },
        desc: {
          th: "เริ่มและหยุดเมื่อไหร่: Hover คลิก ระยะห่าง หรือการเลื่อนหน้า",
          en: "What starts and stops it: hover, click, distance or scroll.",
          zh: "何时开始、何时停止：悬停、点击、距离或滚动。",
          ja: "いつ始まり、いつ止まるか：ホバー、クリック、距離、スクロール。",
        },
        example: "within 100 px of the button",
      },
      {
        key: "Feel",
        label: { th: "จังหวะ", en: "The timing", zh: "节奏", ja: "タイミング" },
        desc: {
          th: "บอกเป็นตัวเลข: 150ms กระชับ 300ms นุ่มนวล หรือสปริงที่เด้งนิด ๆ",
          en: "In numbers: 150 ms is snappy, 300 ms is smooth, a spring adds a slight overshoot.",
          zh: "用数字说明：150 毫秒干脆，300 毫秒顺滑，弹簧会带一点回弹。",
          ja: "数字で伝える：150 ms はきびきび、300 ms はなめらか、バネは少し行き過ぎて戻る。",
        },
        example: "spring back over 400 ms",
      },
      {
        key: "Purpose",
        label: { th: "เป้าหมาย UX", en: "The UX goal", zh: "UX 目标", ja: "UX の目的" },
        desc: {
          th: "ทำไปเพื่ออะไร AI จะเลือกได้ดีขึ้นเมื่อรู้ว่าเป้าหมายคืออะไร",
          en: "Why it exists. AI makes better trade-offs when it knows the goal.",
          zh: "为什么要做。AI 知道目标后，会做出更好的取舍。",
          ja: "なぜ必要か。目的がわかると、AI はより良い判断をします。",
        },
        example: "make the main action feel inviting",
      },
      {
        key: "Guardrails",
        label: { th: "กันพลาด", en: "The guardrails", zh: "防护规则", ja: "ガードレール" },
        desc: {
          th: "ลดการเคลื่อนไหว จอสัมผัส คีย์บอร์ด 60fps และเลย์เอาต์ไม่กระโดด ข้อนี้แหละที่แยกมือโปรออกจากมือใหม่",
          en: "Reduced motion, touch, keyboard, 60 fps, no layout shift. This is what separates pros from beginners.",
          zh: "减少动态效果、触屏、键盘、60 帧、布局不跳动。这正是高手与新手的区别。",
          ja: "動きを減らす設定、タッチ、キーボード、60 fps、レイアウトのずれなし。ここがプロと初心者の差です。",
        },
        example: "respect prefers-reduced-motion",
      },
    ] as { key: string; label: Localized; desc: Localized; example: string }[],
  },
  builder: {
    title: { th: "ลองเขียน Prompt ของคุณเอง", en: "Write your own prompt", zh: "写出你自己的提示词", ja: "自分のプロンプトを書いてみよう" },
    lead: {
      th: "เติมช่องว่างตามสูตร แตะคำแนะนำเพื่อเติมให้เร็วขึ้น แล้วก๊อปไปใช้ได้เลย",
      en: "Fill in the formula — tap a suggestion to go faster — and copy the result.",
      zh: "按公式填空，点击建议可以更快填写，然后复制结果。",
      ja: "公式に沿って埋めましょう。候補をタップすると速く入力できます。できたらコピー。",
    },
    build: { th: "จะสร้างอะไร", en: "What are you building?", zh: "你要做什么？", ja: "何を作りますか？" },
    buildPlaceholder: "a product card",
    effectPlaceholder: "the card flips over to show its back",
    triggerPlaceholder: "on hover",
    feelPlaceholder: "smooth, 300 ms ease-in-out",
    purposePlaceholder: "show the details without leaving the page",
    suggestions: { th: "คำแนะนำ", en: "Suggestions", zh: "建议", ja: "候補" },
    triggers: ["on hover", "on click", "when it scrolls into view", "while dragging", "when the cursor comes near"],
    feels: ["snappy, 150 ms ease-out", "smooth, 300 ms ease-in-out", "springy, with a slight overshoot", "slow and calm, 600 ms"],
    guardrailsLabel: { th: "กันพลาด (แนะนำให้เลือกทั้งหมด)", en: "Guardrails (keep them all on)", zh: "防护规则（建议全部勾选）", ja: "ガードレール（すべてオン推奨）" },
    guardrails: [
      {
        id: "motion",
        label: { th: "เคารพการตั้งค่าลดการเคลื่อนไหว", en: "Respect reduced motion", zh: "遵循减少动态效果设置", ja: "動きを減らす設定を尊重" },
        text: "respect prefers-reduced-motion",
      },
      {
        id: "touch",
        label: { th: "ใช้ได้บนจอสัมผัส", en: "Works on touch screens", zh: "支持触屏", ja: "タッチ操作に対応" },
        text: "work on touch screens",
      },
      {
        id: "keyboard",
        label: { th: "ใช้คีย์บอร์ดได้ และเห็น Focus ชัด", en: "Keyboard accessible, visible focus", zh: "可用键盘操作，焦点清晰可见", ja: "キーボード操作とフォーカス表示" },
        text: "work with a keyboard and keep a visible focus ring",
      },
      {
        id: "perf",
        label: { th: "ลื่น 60fps (transform และ opacity เท่านั้น)", en: "Smooth 60 fps (transform and opacity only)", zh: "流畅 60 帧（只用 transform 和 opacity）", ja: "60 fps（transform と opacity のみ）" },
        text: "animate only transform and opacity for 60 fps",
      },
      {
        id: "layout",
        label: { th: "เลย์เอาต์ไม่กระโดด", en: "No layout shift", zh: "布局不跳动", ja: "レイアウトのずれなし" },
        text: "cause no layout shift",
      },
    ] as { id: string; label: Localized; text: string }[],
    output: { th: "Prompt ของคุณ", en: "Your prompt", zh: "你的提示词", ja: "あなたのプロンプト" },
    empty: {
      th: "เริ่มจากช่อง “จะสร้างอะไร” แล้ว Prompt จะค่อย ๆ ปรากฏที่นี่",
      en: "Start with “What are you building?” and your prompt will build up here.",
      zh: "从“你要做什么？”开始，提示词会在这里逐步生成。",
      ja: "「何を作りますか？」から始めると、ここにプロンプトができていきます。",
    },
  },
  concepts: {
    title: { th: "อยากเข้าใจลึกกว่าเดิม?", en: "Want to go deeper?", zh: "想更深入了解？", ja: "もっと深く知りたい？" },
    lead: {
      th: "ทุกเอฟเฟกต์ตั้งอยู่บนหลักการ UX ไม่กี่ข้อ ลองสัมผัสหลักการเหล่านี้ในคลังศัพท์",
      en: "Every effect here rests on a few UX principles. Experience them in the glossary.",
      zh: "这里的每个特效都建立在少数几条 UX 原则之上。去词汇表里亲身体验吧。",
      ja: "どのエフェクトも、いくつかの UX 原則の上に成り立っています。用語集で体験してみましょう。",
    },
    ids: ["feedback", "affordance", "hover", "accessibility", "usability"],
  },
};
