import type { Concept } from "../types";

export const componentConcepts: Concept[] = [
  {
    id: "button",
    term: "Button",
    ipa: "/ˈbʌt.ən/",
    localTerm: {
      th: "ปุ่ม",
      en: "Call to action (CTA)",
      zh: "按钮",
      ja: "ボタン",
    },
    categories: ["component"],
    difficulty: 1,
    short: {
      th: "องค์ประกอบที่กดแล้วเกิดการกระทำทันที เช่น ส่ง บันทึก หรือซื้อ",
      en: "An element that performs an action when pressed — send, save, buy.",
      zh: "按下后立即执行操作的元素——发送、保存、购买。",
      ja: "押すとすぐにアクションを実行する要素。送信、保存、購入など。",
    },
    instruction: {
      th: "สลับดูหน้าต่างยืนยันสองแบบ แล้วตัดสินใจว่าจะกดปุ่มไหน แบบไหนตัดสินใจได้เร็วกว่ากัน?",
      en: "Switch between the two dialogs and decide which button to press. Which one lets you decide faster?",
      zh: "在两个对话框之间切换，决定要按哪个按钮。哪一个让你更快做出决定？",
      ja: "2 つのダイアログを切り替えて、どのボタンを押すか決めてみましょう。どちらが早く決められますか？",
    },
    demo: "button",
    problem: {
      th: "เมื่อหน้าจอมีหลายปุ่ม ผู้ใช้ต้องรู้ทันทีว่าปุ่มไหนคือการกระทำหลัก และแต่ละปุ่มจะทำอะไร",
      en: "When a screen has several buttons, people need to see instantly which one is the main action — and what each will do.",
      zh: "当屏幕上有多个按钮时，人们需要立刻看出哪个是主要操作，以及每个按钮会做什么。",
      ja: "画面に複数のボタンがあるとき、人はどれがメインのアクションで、それぞれ何が起きるのかを瞬時に知る必要があります。",
    },
    how: {
      th: [
        "ใช้ลำดับชั้นของปุ่ม (Button hierarchy): ปุ่มหลัก (Primary) มีหนึ่งปุ่มต่อหนึ่งงานและเด่นที่สุด ปุ่มรอง (Secondary) ดูเบากว่า และปุ่มระดับสาม (Tertiary) ดูคล้ายลิงก์",
        "ข้อความบนปุ่มควรเป็นคำกริยาที่บอกผลลัพธ์ “ลบโปรเจกต์” ดีกว่า “ตกลง” เพราะผู้ใช้ไม่ต้องอ่านข้อความอื่นก็รู้ว่าจะเกิดอะไรขึ้น",
        "ปุ่มที่ดีต้องออกแบบครบทุกสถานะ: ปกติ ชี้ กด โฟกัส ปิดใช้งาน และกำลังโหลด",
      ],
      en: [
        "Use a button hierarchy: one primary button per task (the most prominent), lighter secondary buttons, and tertiary buttons that look like links.",
        "Labels should be verbs that describe the outcome. “Delete project” beats “OK” — people know what will happen without reading everything else.",
        "Design every state: default, hover, pressed, focus, disabled and loading.",
      ],
      zh: [
        "使用按钮层级：每个任务只有一个主要按钮（最醒目），次要按钮更轻，第三级按钮看起来像链接。",
        "按钮文字应该是描述结果的动词。“删除项目”胜过“确定”——不用读完其他内容就知道会发生什么。",
        "设计好每一种状态：默认、悬停、按下、焦点、禁用和加载。",
      ],
      ja: [
        "ボタンの階層を使います。1 つのタスクにプライマリーボタンは 1 つ（最も目立つ）、セカンダリーは控えめに、ターシャリーはリンクのような見た目に。",
        "ラベルは結果を表す動詞に。「OK」より「プロジェクトを削除」。他の文を読まなくても何が起きるか分かります。",
        "すべての状態をデザインします。デフォルト、ホバー、押下、フォーカス、無効、読み込み中。",
      ],
    },
    inPractice: {
      th: [
        "ปุ่ม “โอนเงิน” ที่เด่นคู่กับปุ่ม “ยกเลิก” ที่เบากว่า",
        "ปุ่มสั่งอาหารที่แสดงราคารวมไว้บนปุ่ม",
        "ปุ่ม “ลบ” สีแดงที่เตือนว่าเป็นการกระทำที่ย้อนกลับไม่ได้",
      ],
      en: [
        "A bold “Transfer” button next to a quieter “Cancel”",
        "Food-delivery buttons that show the total price on the button",
        "Red “Delete” buttons that warn of a destructive action",
      ],
      zh: ["醒目的“转账”按钮旁边是较低调的“取消”按钮", "在按钮上直接显示总价的外卖下单按钮", "用红色提醒危险操作的“删除”按钮"],
      ja: [
        "目立つ「振込」ボタンと、控えめな「キャンセル」ボタン",
        "ボタン上に合計金額を表示するフードデリバリーの注文ボタン",
        "取り消せない操作を警告する赤い「削除」ボタン",
      ],
    },
    mistake: {
      th: "ทำให้ทุกปุ่มเด่นเท่ากัน เมื่อทุกอย่างสำคัญ ก็เท่ากับไม่มีอะไรสำคัญเลย",
      en: "Making every button equally loud. When everything is important, nothing is.",
      zh: "让每个按钮都一样醒目。当一切都重要时，就没有什么是重要的。",
      ja: "すべてのボタンを同じくらい目立たせること。すべてが重要なら、何も重要ではなくなります。",
    },
    takeaway: {
      th: "หนึ่งหน้าจอ หนึ่งปุ่มหลัก และป้ายที่บอกผลลัพธ์",
      en: "One screen, one primary action, and labels that name the outcome.",
      zh: "一个界面，一个主要操作，以及说明结果的标签。",
      ja: "1 つの画面に 1 つのメインアクション。ラベルには結果を書く。",
    },
    related: ["click", "affordance", "active-state", "disabled-state", "loading-state"],
    sources: ["nng-button-states", "hig-buttons", "m3-buttons", "apg-button", "mdn-button"],
    aliases: ["ปุ่ม", "บัตตัน", "cta", "call to action", "primary button", "ボタン", "按钮"],
  },
  {
    id: "input-field",
    term: "Input field",
    ipa: "/ˈɪn.pʊt ˌfiːld/",
    localTerm: {
      th: "ช่องกรอกข้อมูล",
      en: "Text field, form field",
      zh: "输入框",
      ja: "入力フィールド",
    },
    categories: ["component"],
    difficulty: 1,
    short: {
      th: "ช่องที่ให้ผู้ใช้พิมพ์ข้อมูล เช่น ชื่อ อีเมล หรือรหัสผ่าน",
      en: "A box where people type information — a name, an email, a password.",
      zh: "让人输入信息的框——姓名、邮箱、密码。",
      ja: "名前やメールアドレス、パスワードなどを入力する欄。",
    },
    instruction: {
      th: "พิมพ์อีเมลลงในทั้งสองช่อง แล้วลองตรวจทานว่าแต่ละช่องถามอะไร แบบไหนตรวจทานได้ง่ายกว่า?",
      en: "Type an email into both fields, then try to check what each one was asking for. Which is easier to review?",
      zh: "在两个输入框中都输入邮箱，然后检查每个框原本问的是什么。哪一个更容易核对？",
      ja: "両方の欄にメールアドレスを入力してから、それぞれ何を聞かれていたか確認してみましょう。見直しやすいのはどちら？",
    },
    demo: "input-field",
    problem: {
      th: "ฟอร์มคือจุดที่คนยอมแพ้บ่อยที่สุด ช่องที่ไม่ชัดว่าต้องกรอกอะไร หรือแจ้งข้อผิดพลาดไม่ดี ทำให้คนเลิกกลางทาง",
      en: "Forms are where people give up most often. Fields that don’t say what they want, or that report errors badly, make people quit halfway.",
      zh: "表单是人们最常放弃的地方。没说清楚要填什么、或者报错方式糟糕的输入框，会让人中途放弃。",
      ja: "フォームは人が最もあきらめやすい場所です。何を入力するのか分からない欄や、エラーの伝え方が悪い欄は、途中離脱を招きます。",
    },
    how: {
      th: [
        "ป้ายกำกับ (Label) ควรอยู่เหนือช่องและมองเห็นตลอดเวลา อย่าใช้ Placeholder แทน Label เพราะมันหายไปทันทีที่เริ่มพิมพ์",
        "ใช้ข้อความช่วยเหลือ (Helper text) บอกรูปแบบที่ต้องการไว้ล่วงหน้า และเรียกคีย์บอร์ดให้ตรงกับข้อมูล เช่น คีย์บอร์ดตัวเลขสำหรับเบอร์โทร",
        "ตรวจสอบหลังผู้ใช้กรอกช่องนั้นเสร็จ ไม่ใช่ระหว่างพิมพ์ และบอกวิธีแก้ที่ชัดเจนไว้ใต้ช่องนั้นเลย",
      ],
      en: [
        "Keep a visible label above the field at all times. Don’t use placeholder text as the label — it vanishes the moment people start typing.",
        "Use helper text to state the expected format up front, and request the right keyboard — a number pad for phone numbers.",
        "Validate after people finish a field, not while they type, and put a clear fix right below that field.",
      ],
      zh: [
        "始终在输入框上方保留可见的标签。不要用占位文字代替标签——一开始输入它就消失了。",
        "用辅助说明提前写明格式要求，并调用合适的键盘——比如输入电话号码时显示数字键盘。",
        "在用户填完一个字段后再校验，而不是边输入边校验；并在该字段正下方写明修改方法。",
      ],
      ja: [
        "見えるラベルを常に欄の上に置きます。プレースホルダーをラベル代わりにしないこと。入力を始めた瞬間に消えてしまいます。",
        "補足テキストで期待される形式を先に伝え、データに合ったキーボードを表示します（電話番号なら数字キーパッド）。",
        "入力中ではなく入力し終えてから検証し、その欄のすぐ下に分かりやすい直し方を示します。",
      ],
    },
    inPractice: {
      th: [
        "ช่องเบอร์โทรที่เปิดคีย์บอร์ดตัวเลขให้อัตโนมัติ",
        "ช่องรหัสผ่านที่มีปุ่ม “แสดงรหัสผ่าน”",
        "ช่องค้นหาที่แนะนำคำให้ระหว่างพิมพ์",
      ],
      en: [
        "Phone-number fields that open a number pad automatically",
        "Password fields with a “Show password” button",
        "Search fields that suggest terms as you type",
      ],
      zh: ["自动弹出数字键盘的手机号输入框", "带“显示密码”按钮的密码框", "边输入边给出建议的搜索框"],
      ja: ["自動で数字キーパッドが開く電話番号欄", "「パスワードを表示」ボタン付きのパスワード欄", "入力中に候補を提案する検索欄"],
    },
    mistake: {
      th: "ใช้ Placeholder เป็นป้ายกำกับ เมื่อพิมพ์แล้วผู้ใช้จะจำไม่ได้ว่าช่องนี้ถามอะไร และโปรแกรมอ่านหน้าจอบางตัวก็ไม่อ่านมันเลย",
      en: "Using placeholder text as the label. Once people type, they forget what the field asked — and some screen readers never announce it.",
      zh: "用占位文字充当标签。一旦开始输入，人们就忘了这个框问的是什么——有些读屏软件甚至根本不会读出它。",
      ja: "プレースホルダーをラベルとして使うこと。入力すると何を聞かれていたか忘れてしまい、スクリーンリーダーが読み上げないこともあります。",
    },
    takeaway: {
      th: "ป้ายกำกับต้องมองเห็นเสมอ ข้อผิดพลาดต้องบอกวิธีแก้",
      en: "Labels stay visible. Errors explain the fix.",
      zh: "标签始终可见，错误提示要说明怎么改。",
      ja: "ラベルは常に見えるように。エラーは直し方を伝える。",
    },
    related: ["error-state", "focus-state", "success-state", "dropdown"],
    sources: ["nng-placeholders", "nng-web-forms", "govuk-text-input", "hig-text-fields"],
    aliases: ["ช่องกรอก", "ฟอร์ม", "text field", "textbox", "form", "placeholder", "入力欄", "テキストフィールド", "输入框", "表单"],
  },
  {
    id: "dropdown",
    term: "Dropdown",
    ipa: "/ˈdrɒp.daʊn/",
    localTerm: {
      th: "ดรอปดาวน์ · เมนูแบบเลื่อนลง",
      en: "Select menu, picker",
      zh: "下拉菜单",
      ja: "ドロップダウン",
    },
    categories: ["component"],
    difficulty: 2,
    short: {
      th: "ปุ่มเลือกที่ซ่อนรายการตัวเลือกไว้ และแสดงออกมาเมื่อกด เพื่อเลือกหนึ่งค่า",
      en: "A compact control that reveals a list of options when opened, so you can pick one.",
      zh: "一个紧凑的控件，点开后显示选项列表，从中选择一个。",
      ja: "開くと選択肢の一覧が表示され、その中から 1 つを選べるコンパクトなコントロール。",
    },
    instruction: {
      th: "เลือกไซซ์เสื้อด้วยทั้งสองแบบ แบบไหนใช้คลิกน้อยกว่า และเห็นตัวเลือกได้ทันที?",
      en: "Choose a T-shirt size with both versions. Which takes fewer clicks — and shows the options straight away?",
      zh: "用两种方式选择 T 恤尺码。哪一种点击次数更少，并且能直接看到所有选项？",
      ja: "2 つの方法で T シャツのサイズを選んでみましょう。クリックが少なく、選択肢がすぐ見えるのはどちら？",
    },
    demo: "dropdown",
    problem: {
      th: "ตัวเลือกจำนวนมากกินพื้นที่หน้าจอ Dropdown ช่วยประหยัดพื้นที่ แต่แลกกับการที่ตัวเลือกถูกซ่อน และต้องคลิกเพิ่ม",
      en: "Long lists of options eat screen space. A dropdown saves room — but at the cost of hiding the choices and adding clicks.",
      zh: "大量选项会占用屏幕空间。下拉菜单节省了空间，但代价是隐藏了选项并增加了点击次数。",
      ja: "選択肢が多いと画面を圧迫します。ドロップダウンは場所を節約しますが、そのぶん選択肢が隠れ、クリックが増えます。",
    },
    how: {
      th: [
        "ตัวเลือกไม่เกิน 5 ข้อ: ใช้ Radio button เพื่อให้เห็นทุกตัวเลือกพร้อมกันและเลือกได้ในคลิกเดียว",
        "ประมาณ 5–15 ข้อ: Dropdown เหมาะเมื่อพื้นที่จำกัด ส่วนรายการที่ยาวมาก เช่น รายชื่อประเทศ ควรพิมพ์ค้นหาได้",
        "ถ้าผู้ใช้ส่วนใหญ่เลือกค่าเดียวกัน ให้ตั้งค่าเริ่มต้นที่เหมาะสมไว้ก่อน แต่อย่าเดาแทนผู้ใช้ในเรื่องที่สำคัญ",
      ],
      en: [
        "Five options or fewer: use radio buttons, so every choice is visible and takes one click.",
        "Roughly 5–15 options: a dropdown works when space is tight. For very long lists (like countries), let people type to search.",
        "If most people pick the same value, preselect a sensible default — but don’t guess on decisions that really matter.",
      ],
      zh: [
        "5 个或更少选项：使用单选按钮，让所有选项一目了然，一次点击即可。",
        "大约 5–15 个选项：空间紧张时适合用下拉菜单。很长的列表（比如国家）应该支持输入搜索。",
        "如果大多数人选同一个值，可以预先选好合理的默认值——但在真正重要的决定上不要替用户猜。",
      ],
      ja: [
        "選択肢が 5 つ以下なら、ラジオボタンを使い、すべてを見せて 1 クリックで選べるようにします。",
        "5〜15 個程度なら、スペースが限られる場合にドロップダウンが向いています。国名のような長いリストは入力して検索できるように。",
        "ほとんどの人が同じ値を選ぶなら、妥当な初期値を設定します。ただし重要な判断を勝手に推測しないこと。",
      ],
    },
    inPractice: {
      th: [
        "เลือกจังหวัดในฟอร์มที่อยู่",
        "เลือกภาษาหรือสกุลเงินบนเว็บไซต์",
        "เรียงลำดับสินค้า “ราคาต่ำไปสูง”",
      ],
      en: [
        "Picking a county or region in an address form",
        "Choosing a language or currency on a website",
        "Sorting products by “Price: low to high”",
      ],
      zh: ["在地址表单中选择省份", "在网站上选择语言或货币", "按“价格从低到高”排序商品"],
      ja: ["住所フォームで都道府県を選ぶ", "Web サイトで言語や通貨を選ぶ", "商品を「価格の安い順」に並べ替える"],
    },
    mistake: {
      th: "ใช้ Dropdown กับตัวเลือกแค่ 2–3 ข้อ เช่น ใช่/ไม่ใช่ ซึ่งเพิ่มคลิกโดยไม่จำเป็น และซ่อนสิ่งที่ควรเห็นได้ทันที",
      en: "Using a dropdown for just 2–3 options like Yes/No — it adds clicks for nothing and hides what could be seen at a glance.",
      zh: "只有 2–3 个选项（比如“是/否”）也用下拉菜单——白白增加点击，还把一眼就能看到的内容藏了起来。",
      ja: "「はい／いいえ」のような 2〜3 個の選択肢にドロップダウンを使うこと。無駄にクリックが増え、ひと目で見えるはずのものが隠れます。",
    },
    takeaway: {
      th: "ตัวเลือกน้อย ให้เห็นทั้งหมด ตัวเลือกเยอะ ค่อยพับเก็บ",
      en: "Few options? Show them all. Many options? Then fold them away.",
      zh: "选项少就全部展示，选项多再收起来。",
      ja: "選択肢が少ないなら全部見せる。多いときにだけ畳む。",
    },
    related: ["input-field", "button", "usability"],
    sources: ["nng-listbox-dropdown", "nng-dropdowns", "nng-radio-checkbox", "apg-combobox", "hig-pull-down", "m3-menus", "govuk-radios"],
    aliases: ["ดรอปดาวน์", "เมนูเลื่อนลง", "select", "picker", "listbox", "ドロップダウン", "下拉"],
  },
  {
    id: "tooltip",
    term: "Tooltip",
    ipa: "/ˈtuːl.tɪp/",
    localTerm: {
      th: "ทูลทิป · ป้ายคำอธิบายสั้น",
      en: "Hint, info tip",
      zh: "工具提示",
      ja: "ツールチップ",
    },
    categories: ["component"],
    difficulty: 1,
    short: {
      th: "ข้อความสั้น ๆ ที่ปรากฏเมื่อชี้หรือโฟกัสที่องค์ประกอบ เพื่ออธิบายว่ามันคืออะไรหรือทำอะไร",
      en: "A short label that appears when you point at or focus an element, explaining what it is or does.",
      zh: "指向或聚焦某个元素时出现的简短文字，说明它是什么或能做什么。",
      ja: "要素にポインターを合わせたりフォーカスしたりすると表示される短いラベル。それが何か、何をするかを説明します。",
    },
    instruction: {
      th: "ชี้เมาส์หรือกด Tab ไปที่ไอคอนในแถบเครื่องมือ แล้วลองกด Esc เพื่อปิดทูลทิป",
      en: "Point at — or Tab to — the toolbar icons. Then press Esc to dismiss a tooltip.",
      zh: "用鼠标指向或用 Tab 键移到工具栏图标上，然后按 Esc 关闭提示。",
      ja: "ツールバーのアイコンにポインターを合わせるか Tab で移動し、Esc でツールチップを閉じてみましょう。",
    },
    demo: "tooltip",
    problem: {
      th: "ไอคอนช่วยประหยัดพื้นที่ แต่ไม่ใช่ทุกไอคอนที่ทุกคนเข้าใจ ทูลทิปช่วยบอกชื่อโดยไม่ทำให้หน้าจอรก",
      en: "Icons save space, but not every icon is obvious. Tooltips name them without cluttering the screen.",
      zh: "图标节省空间，但并非每个图标都一看就懂。工具提示可以说明它们的名称，又不会让屏幕变得杂乱。",
      ja: "アイコンは場所を節約しますが、すべてが分かりやすいわけではありません。ツールチップなら画面を散らかさずに名前を伝えられます。",
    },
    how: {
      th: [
        "ทูลทิปควรสั้น (ไม่กี่คำ) และเป็นข้อมูล “เสริม” เท่านั้น ข้อมูลที่ผู้ใช้จำเป็นต้องรู้เพื่อทำงานให้สำเร็จ ต้องแสดงบนหน้าจอเลย",
        "ต้องเปิดได้ทั้งด้วยการชี้เมาส์และการโฟกัสด้วยคีย์บอร์ด ปิดได้ด้วย Esc และไม่หายไปเมื่อเมาส์ขยับไปบนตัวทูลทิป",
        "มือถือไม่มี Hover ทูลทิปจึงใช้ได้จำกัด ไอคอนสำคัญควรมีป้ายข้อความกำกับไว้เลย",
      ],
      en: [
        "Keep tooltips brief — a few words — and supplementary. Anything people need to complete the task should be visible on the page.",
        "They must open on both hover and keyboard focus, close with Esc, and stay open while the pointer moves onto them.",
        "Phones have no hover, so tooltips barely work there. Important icons deserve a visible text label instead.",
      ],
      zh: [
        "工具提示要简短（几个词）并且只提供补充信息。完成任务所必需的信息，应该直接显示在页面上。",
        "它必须在悬停和键盘聚焦时都能出现，可以用 Esc 关闭，并且在指针移到提示上时保持显示。",
        "手机没有悬停，工具提示在手机上几乎无效。重要的图标应该直接配上可见的文字标签。",
      ],
      ja: [
        "ツールチップは短く（数語）、あくまで補足に。作業を終えるのに必要な情報は、ページ上に表示します。",
        "ホバーとキーボードフォーカスの両方で表示され、Esc で閉じられ、ポインターをツールチップの上に移しても消えないこと。",
        "スマホにはホバーがないので、ツールチップはほとんど機能しません。重要なアイコンには、見えるテキストラベルを付けましょう。",
      ],
    },
    inPractice: {
      th: [
        "ชื่อปุ่มในแถบเครื่องมือของโปรแกรมแต่งรูปหรือเอกสาร",
        "คำอธิบายของไอคอน “i” ข้างช่องกรอกข้อมูล",
        "คำใบ้ปุ่มลัดคีย์บอร์ดในเครื่องมืออย่าง Figma หรือ Google Docs",
      ],
      en: [
        "Toolbar button names in photo and document editors",
        "Explanations behind “i” icons next to form fields",
        "Keyboard-shortcut hints in tools like Figma or Google Docs",
      ],
      zh: ["图片和文档编辑器中工具栏按钮的名称", "表单字段旁“i”图标后面的说明", "Figma 或 Google 文档中的快捷键提示"],
      ja: [
        "写真編集や文書作成ツールのツールバーボタン名",
        "入力欄の横にある「i」アイコンの説明",
        "Figma や Google ドキュメントのキーボードショートカットのヒント",
      ],
    },
    mistake: {
      th: "ใส่เงื่อนไขสำคัญ เช่น กฎของรหัสผ่าน ไว้ในทูลทิป ผู้ใช้จะเห็นมันก็ต่อเมื่อทำผิดไปแล้ว",
      en: "Putting essential rules — like password requirements — inside a tooltip. People only find them after they’ve already failed.",
      zh: "把关键规则（比如密码要求）放进工具提示里。人们往往在出错之后才发现它们。",
      ja: "パスワードの条件のような必須のルールをツールチップに入れること。失敗してから初めて気づくことになります。",
    },
    takeaway: {
      th: "ทูลทิปมีไว้ช่วย ไม่ใช่มีไว้ซ่อนสิ่งที่จำเป็น",
      en: "Tooltips help; they must never hide what’s essential.",
      zh: "工具提示是用来帮忙的，绝不能用来隐藏必要信息。",
      ja: "ツールチップは助けるためのもの。必要な情報を隠すためのものではない。",
    },
    related: ["hover", "focus-state", "accessibility", "affordance"],
    sources: ["nng-tooltips", "nng-info-tips", "apg-tooltip", "wcag-hover-focus", "m3-tooltips"],
    aliases: ["ทูลทิป", "คำใบ้", "hint", "info tip", "ツールチップ", "提示"],
  },
  {
    id: "modal",
    term: "Modal",
    ipa: "/ˈməʊ.dəl/",
    localTerm: {
      th: "โมดัล · หน้าต่างที่ซ้อนขึ้นมา",
      en: "Modal dialog",
      zh: "模态对话框",
      ja: "モーダル",
    },
    categories: ["component"],
    difficulty: 2,
    short: {
      th: "หน้าต่างที่ซ้อนขึ้นมาบนหน้าจอ และให้ผู้ใช้ตอบก่อนจึงจะทำอย่างอื่นต่อได้",
      en: "A window that appears on top of the page and asks for a response before you can continue.",
      zh: "出现在页面上方的窗口，要求你先作出回应才能继续。",
      ja: "ページの上に重なって表示され、応答するまで先へ進めないウィンドウ。",
    },
    instruction: {
      th: "กด “ลบโปรเจกต์” แล้วลองใช้ปุ่ม Tab, Esc หรือคลิกพื้นหลัง สังเกตว่าโฟกัสถูกเก็บไว้ในหน้าต่างอย่างไร",
      en: "Press “Delete project”, then try Tab, Esc or clicking the background. Notice how focus stays inside the dialog.",
      zh: "点击“删除项目”，然后试试 Tab、Esc 或点击背景。留意焦点是如何被留在对话框内的。",
      ja: "「プロジェクトを削除」を押して、Tab、Esc、背景のクリックを試してみましょう。フォーカスがダイアログ内に留まる様子に注目。",
    },
    demo: "modal",
    problem: {
      th: "บางการตัดสินใจสำคัญเกินกว่าจะพลาด เช่น การลบข้อมูลถาวร ระบบจึงต้อง “หยุด” ผู้ใช้ไว้ชั่วครู่เพื่อยืนยัน",
      en: "Some decisions are too important to miss — like permanently deleting data — so the interface needs to pause people for a moment to confirm.",
      zh: "有些决定重要到不容错过——比如永久删除数据——因此界面需要让人们暂停片刻进行确认。",
      ja: "データの完全削除のように、見逃してはいけない重要な判断があります。そのとき画面は、確認のために一瞬ユーザーを立ち止まらせる必要があります。",
    },
    how: {
      th: [
        "Modal จะ “ล็อก” หน้าข้างหลังไว้ ทั้งเมาส์และคีย์บอร์ดใช้งานได้เฉพาะในหน้าต่างนี้ จนกว่าผู้ใช้จะตอบหรือปิดมัน",
        "Modal ที่ดีต้องปิดได้เสมอ (ปุ่มยกเลิก หรือปุ่ม Esc) และเมื่อปิดแล้ว โฟกัสต้องกลับไปที่ปุ่มเดิมที่เปิดมัน",
        "เพราะ Modal ขัดจังหวะการทำงาน จึงควรใช้เฉพาะเรื่องสำคัญที่ต้องตัดสินใจทันที ไม่ใช่ใช้ขายโฆษณาหรือขอให้สมัครรับข่าวสาร",
      ],
      en: [
        "A modal locks the page behind it: mouse and keyboard only work inside the dialog until you respond or close it.",
        "A good modal can always be dismissed (Cancel, the Esc key), and when it closes, focus returns to the button that opened it.",
        "Because modals interrupt, save them for important decisions that need an answer now — not for adverts or newsletter sign-ups.",
      ],
      zh: [
        "模态对话框会锁住后面的页面：在你回应或关闭之前，鼠标和键盘只能在对话框内操作。",
        "好的模态对话框总能被关闭（取消按钮、Esc 键），关闭后焦点会回到打开它的那个按钮上。",
        "因为模态会打断用户，所以只应在需要立即作答的重要决定时使用——而不是用于广告或订阅邮件。",
      ],
      ja: [
        "モーダルは背後のページをロックします。応答するか閉じるまで、マウスもキーボードもダイアログ内でしか動きません。",
        "良いモーダルはいつでも閉じられ（キャンセル、Esc キー）、閉じたらフォーカスは開いたボタンに戻ります。",
        "モーダルは作業を中断させるので、今すぐ答えが必要な重要な判断にだけ使います。広告やニュースレター登録には使いません。",
      ],
    },
    inPractice: {
      th: [
        "“ยืนยันการลบบัญชี?” ในแอปต่าง ๆ",
        "หน้าต่างยืนยันรายละเอียดก่อนกดโอนเงิน",
        "การขอสิทธิ์เข้าถึงตำแหน่งหรือกล้อง",
      ],
      en: [
        "“Delete your account?” confirmations",
        "Final confirmation before sending a bank transfer",
        "Requests for location or camera permission",
      ],
      zh: ["“确认删除账户？”这类确认框", "银行转账发送前的最终确认", "请求获取位置或相机权限"],
      ja: ["「アカウントを削除しますか？」の確認", "振込を送信する前の最終確認", "位置情報やカメラへのアクセス許可のリクエスト"],
    },
    mistake: {
      th: "เด้ง Modal ขึ้นมาทันทีที่เปิดเว็บเพื่อขอให้สมัครสมาชิก ทั้งที่ผู้ใช้ยังไม่ทันรู้ด้วยซ้ำว่าเว็บนี้คืออะไร",
      en: "Popping a modal the instant the page loads to ask for a sign-up — before people even know what the site is.",
      zh: "页面一打开就弹出模态框要求注册——人们甚至还不知道这个网站是做什么的。",
      ja: "ページを開いた瞬間にモーダルで会員登録を求めること。そのサイトが何なのかさえ、まだ分かっていないのに。",
    },
    takeaway: {
      th: "ใช้ Modal เมื่อจำเป็นต้องหยุดผู้ใช้จริง ๆ และเปิดทางออกไว้เสมอ",
      en: "Use a modal only when you must stop someone — and always leave a way out.",
      zh: "只有在必须让人停下来时才用模态，并且永远留一条出路。",
      ja: "モーダルは、どうしても立ち止まってもらう必要があるときだけ。必ず出口を用意する。",
    },
    related: ["button", "focus-state", "accessibility", "feedback"],
    sources: ["nng-modal", "nng-popups", "apg-dialog", "hig-modality", "mdn-dialog"],
    aliases: ["โมดัล", "ป๊อปอัป", "popup", "dialog", "ไดอะล็อก", "モーダル", "ダイアログ", "弹窗", "模态", "对话框"],
  },
];
