import type { Concept } from "../types";

export const interactionConcepts: Concept[] = [
  {
    id: "hover",
    term: "Hover",
    ipa: "/ˈhɒv.ə/",
    localTerm: {
      th: "โฮเวอร์ · การวางเมาส์เหนือองค์ประกอบ",
      en: "Mouse-over",
      zh: "悬停",
      ja: "ホバー（マウスオーバー）",
    },
    categories: ["interaction", "state"],
    difficulty: 1,
    short: {
      th: "การวางเมาส์ไว้เหนือองค์ประกอบโดยไม่คลิก เพื่อให้หน้าจอบอกว่า “สิ่งนี้โต้ตอบได้”",
      en: "Resting the pointer over an element without clicking — and the interface answering, “yes, this is interactive”.",
      zh: "把鼠标指针停在某个元素上但不点击，界面借此告诉你“这个可以交互”。",
      ja: "クリックせずにポインターを要素の上に置くこと。画面は「これは操作できます」と応えます。",
    },
    instruction: {
      th: "เลื่อนเมาส์ไปวางบนการ์ดด้านล่าง แล้วสังเกตว่ามีอะไรเปลี่ยนไปบ้าง",
      en: "Move your pointer over the card below and notice everything that changes.",
      zh: "把鼠标移到下方的卡片上，留意有哪些变化。",
      ja: "下のカードにポインターを重ねて、何が変わるか観察してみましょう。",
    },
    peek: {
      th: "เลื่อนเมาส์ไปบนการ์ดเมนู",
      en: "Move your pointer over the card",
      zh: "把指针移到卡片上",
      ja: "カードにポインターを乗せて",
    },
    demo: "hover",
    problem: {
      th: "บนหน้าจอที่เต็มไปด้วยข้อความและรูป ผู้ใช้ไม่รู้ว่าอะไรคลิกได้บ้าง Hover ช่วยยืนยันก่อนที่เขาจะตัดสินใจคลิก",
      en: "On a screen full of text and images, people can’t always tell what’s clickable. Hover confirms it before they commit to a click.",
      zh: "在满是文字和图片的屏幕上，人们并不总能分辨哪些可以点击。悬停在用户点击之前就给出确认。",
      ja: "文字や画像であふれた画面では、どれがクリックできるのか分かりにくいものです。ホバーは、クリックする前にそれを確かめさせてくれます。",
    },
    how: {
      th: [
        "เมื่อเมาส์เข้ามาในพื้นที่ขององค์ประกอบ ระบบควรตอบสนองแทบทันที (ภายในราว 0.1 วินาที) เช่น เปลี่ยนสีพื้นหลัง ยกการ์ดขึ้นเล็กน้อย หรือเปลี่ยนเคอร์เซอร์เป็นรูปมือ",
        "Hover เป็น “การบอกใบ้” ไม่ใช่ “การกระทำ” มันช่วยให้ผู้ใช้มั่นใจก่อนคลิก แต่ไม่ควรเปลี่ยนสิ่งสำคัญบนหน้าจอโดยที่ผู้ใช้ไม่ได้ตั้งใจ",
        "จอสัมผัสไม่มี Hover เพราะนิ้วไม่สามารถลอยอยู่เหนือจอได้ ทุกอย่างที่ซ่อนไว้หลัง Hover จึงต้องเข้าถึงได้ด้วยวิธีอื่นด้วย",
      ],
      en: [
        "When the pointer enters an element, the interface should respond almost instantly (within about 0.1 seconds): a background tint, a gentle lift, or the pointer turning into a hand.",
        "Hover is a hint, not an action. It builds confidence before a click, but it shouldn’t change anything important on its own.",
        "Touch screens have no hover — a finger can’t float above glass. Anything revealed on hover must also be reachable another way.",
      ],
      zh: [
        "指针进入元素时，界面应几乎立即（约 0.1 秒内）做出反应：背景变色、轻微浮起，或指针变成手形。",
        "悬停是一种提示，而不是一次操作。它在点击前给人信心，但不应自行改变任何重要内容。",
        "触屏没有悬停——手指无法悬浮在屏幕上方。任何通过悬停显示的内容，都必须有其他方式可以访问。",
      ],
      ja: [
        "ポインターが要素に入ったら、ほぼ即座に（約 0.1 秒以内）反応させます。背景色の変化、わずかな浮き上がり、ポインターが手の形に変わる、などです。",
        "ホバーは「ヒント」であって「操作」ではありません。クリック前に安心感を与えますが、それだけで重要な何かを変えてはいけません。",
        "タッチスクリーンにはホバーがありません。指は画面の上に浮かべないからです。ホバーで表示する内容は、必ず別の方法でもたどり着けるようにします。",
      ],
    },
    inPractice: {
      th: [
        "ลิงก์ที่ขีดเส้นใต้หรือเปลี่ยนสีเมื่อชี้",
        "การ์ดสินค้าบนเว็บช้อปปิ้งที่ยกขึ้นและแสดงปุ่ม “ใส่ตะกร้า”",
        "เมนูบนเว็บไซต์ที่ไฮไลต์หัวข้อที่กำลังชี้อยู่",
      ],
      en: [
        "Links that underline or change colour when pointed at",
        "Product cards that lift and reveal “Add to basket” on shopping sites",
        "Navigation menus that highlight the item under the pointer",
      ],
      zh: ["鼠标指向时出现下划线或变色的链接", "购物网站上浮起并显示“加入购物车”的商品卡片", "高亮显示当前指向项目的导航菜单"],
      ja: [
        "ポインターを合わせると下線が出たり色が変わるリンク",
        "ショッピングサイトで浮き上がり「カートに入れる」が出る商品カード",
        "ポインター下の項目をハイライトするナビゲーションメニュー",
      ],
    },
    mistake: {
      th: "ซ่อนข้อมูลสำคัญหรือปุ่มหลักไว้หลัง Hover คนใช้มือถือจะไม่มีทางเห็นมันเลย",
      en: "Hiding essential information or the main action behind hover — people on phones will never see it.",
      zh: "把关键信息或主要操作藏在悬停之后——手机用户将永远看不到它。",
      ja: "重要な情報やメインのアクションをホバーの裏に隠すこと。スマホのユーザーには永遠に見えません。",
    },
    takeaway: {
      th: "Hover ใช้ยืนยัน ไม่ใช่ใช้ซ่อน",
      en: "Use hover to confirm, never to hide.",
      zh: "悬停用来确认，而不是用来隐藏。",
      ja: "ホバーは「確かめる」ために使い、「隠す」ためには使わない。",
    },
    related: ["click", "affordance", "tooltip", "focus-state"],
    sources: ["nng-hover-timing", "nng-clickable", "hig-pointing", "wcag-hover-focus"],
    aliases: ["โฮเวอร์", "ชี้เมาส์", "mouseover", "mouse over", "ホバー", "マウスオーバー", "悬停"],
  },
  {
    id: "click",
    term: "Click",
    ipa: "/klɪk/",
    localTerm: {
      th: "คลิก · แตะ (บนมือถือ)",
      en: "Tap (on touch screens)",
      zh: "点击（触屏上为“轻点”）",
      ja: "クリック／タップ",
    },
    categories: ["interaction"],
    difficulty: 1,
    short: {
      th: "การกดเลือกหรือสั่งงานองค์ประกอบด้วยเมาส์ หรือการแตะด้วยนิ้วบนจอสัมผัส",
      en: "Pressing and releasing on an element to select it or trigger an action — a tap on touch screens.",
      zh: "在元素上按下并松开，以选择它或触发操作；在触屏上就是“轻点”。",
      ja: "要素の上で押して離し、選択したり操作を実行したりすること。タッチスクリーンでは「タップ」。",
    },
    instruction: {
      th: "ลองคลิกเป้าทั้งสองแบบให้โดนแบบละ 5 ครั้ง แล้วดูว่าแบบไหนพลาดบ่อยกว่า",
      en: "Try to hit each target five times and see which one you miss more often.",
      zh: "分别点中两个目标各 5 次，看看哪个更容易点偏。",
      ja: "2 つのターゲットをそれぞれ 5 回クリックして、どちらがミスしやすいか比べてみましょう。",
    },
    peek: {
      th: "กดเป้าทั้งสองให้โดนอย่างละ 3 ครั้ง",
      en: "Hit both targets three times",
      zh: "两个目标各点中 3 次",
      ja: "両方の的を 3 回ずつ押して",
    },
    demo: "click",
    problem: {
      th: "ปุ่มที่เล็กหรืออยู่ไกลทำให้ผู้ใช้กดพลาด เสียเวลา และหงุดหงิด โดยเฉพาะบนมือถือหรือเมื่อใช้งานระหว่างเดินทาง",
      en: "Small or distant targets make people miss, waste time and feel clumsy — especially on phones or on the move.",
      zh: "太小或太远的目标会让人点偏、浪费时间、感到笨拙——尤其是在手机上或移动中使用时。",
      ja: "小さすぎたり遠すぎたりするターゲットは、ミスや時間のロス、もどかしさを生みます。スマホや移動中ならなおさらです。",
    },
    how: {
      th: [
        "คลิกที่ดีต้องมีสามช่วง: ก่อนกด (ดูออกว่ากดได้) ระหว่างกด (ปุ่มยุบลงหรือเปลี่ยนสี) และหลังกด (ผลลัพธ์ปรากฏชัดเจน)",
        "กฎของ Fitts บอกว่ายิ่งเป้าใหญ่และอยู่ใกล้ ยิ่งกดได้เร็วและแม่นยำ ปุ่มสำคัญจึงควรใหญ่พอและอยู่ในตำแหน่งที่เอื้อมถึงง่าย",
        "บนจอสัมผัส เป้าแต่ละอันควรมีขนาดราว 44 พอยต์ตามแนวทางของ Apple ส่วน WCAG 2.2 กำหนดขั้นต่ำไว้ที่ 24×24 พิกเซลพร้อมระยะห่างที่เพียงพอ",
      ],
      en: [
        "A good click has three moments: before (it looks pressable), during (it visibly presses in) and after (the result clearly appears).",
        "Fitts’s Law: the bigger and closer a target, the faster and more accurately people hit it. Important actions deserve generous, reachable targets.",
        "On touch screens, aim for roughly 44 points per target (Apple’s guidance). WCAG 2.2 sets a floor of 24×24 CSS pixels with enough spacing.",
      ],
      zh: [
        "好的点击有三个时刻：点击前（看得出能按）、按下时（明显被按下）和点击后（结果清楚出现）。",
        "费茨定律：目标越大、距离越近，人们点得越快越准。重要操作值得更大、更容易够到的目标。",
        "在触屏上，每个目标建议约 44 点（Apple 的建议）。WCAG 2.2 规定最低为 24×24 CSS 像素，并需留出足够间距。",
      ],
      ja: [
        "良いクリックには 3 つの瞬間があります。押す前（押せそうに見える）、押している間（へこんで見える）、押した後（結果がはっきり表示される）。",
        "フィッツの法則：ターゲットが大きく近いほど、人は速く正確に押せます。重要なアクションには、大きく届きやすいターゲットを。",
        "タッチ画面では 1 つのターゲットを約 44 ポイント（Apple の推奨）に。WCAG 2.2 は最低 24×24 CSS ピクセルと十分な間隔を求めています。",
      ],
    },
    inPractice: {
      th: [
        "ปุ่ม “ชำระเงิน” ขนาดใหญ่เต็มความกว้างในแอปธนาคาร",
        "ลิงก์ในข้อความที่มีพื้นที่กดกว้างกว่าตัวอักษร",
        "ไอคอนเล็ก ๆ ที่มีพื้นที่กดรอบตัวใหญ่กว่าที่ตาเห็น",
      ],
      en: [
        "Full-width “Pay now” buttons in banking apps",
        "Text links with a hit area larger than the letters",
        "Small icons whose tappable area is bigger than what you see",
      ],
      zh: ["银行 App 中通栏的“立即支付”按钮", "点击区域比文字本身更大的文本链接", "可点击区域大于视觉大小的小图标"],
      ja: [
        "銀行アプリの横幅いっぱいの「今すぐ支払う」ボタン",
        "文字よりも押せる範囲が広いテキストリンク",
        "見た目より大きなタップ領域を持つ小さなアイコン",
      ],
    },
    mistake: {
      th: "วางปุ่มเล็ก ๆ หลายปุ่มชิดกัน เช่น “แก้ไข” ติดกับ “ลบ” กดพลาดครั้งเดียวอาจเสียข้อมูลทั้งหมด",
      en: "Packing tiny buttons side by side — like “Edit” right next to “Delete”. One slip can cost someone their data.",
      zh: "把小按钮紧挨着摆放——比如“编辑”紧挨着“删除”。一次失误就可能让人丢失数据。",
      ja: "小さなボタンを隙間なく並べること。たとえば「編集」のすぐ隣に「削除」。一度のミスでデータを失いかねません。",
    },
    takeaway: {
      th: "ทำเป้าให้ใหญ่พอ อยู่ใกล้พอ และตอบสนองทุกครั้งที่ถูกกด",
      en: "Make targets big enough, close enough, and responsive every single time.",
      zh: "让目标足够大、足够近，并且每次点击都有回应。",
      ja: "ターゲットは十分に大きく、十分に近く、そして押すたびに必ず反応させる。",
    },
    related: ["button", "feedback", "active-state", "hover"],
    sources: ["laws-fitts", "wcag-target-size", "webdev-tap-targets", "hig-buttons"],
    aliases: ["คลิก", "แตะ", "กด", "tap", "fitts", "target size", "タップ", "クリック", "点击", "轻点"],
  },
  {
    id: "scroll",
    term: "Scroll",
    ipa: "/skrəʊl/",
    localTerm: {
      th: "สกรอลล์ · การเลื่อนหน้าจอ",
      en: "Scrolling",
      zh: "滚动",
      ja: "スクロール",
    },
    categories: ["interaction"],
    difficulty: 1,
    short: {
      th: "การเลื่อนเนื้อหาขึ้นลงหรือซ้ายขวา เพื่อดูส่วนที่ล้นออกนอกจอ",
      en: "Moving content up and down (or sideways) to reveal what doesn’t fit on the screen.",
      zh: "上下（或左右）移动内容，查看屏幕放不下的部分。",
      ja: "画面に収まらない部分を見るために、コンテンツを上下（または左右）に動かすこと。",
    },
    instruction: {
      th: "เลื่อนอ่านบทความสั้นในกรอบด้านล่างจนจบ แล้วสังเกตแถบความคืบหน้าด้านบน",
      en: "Scroll the short article in the box below to the end, and watch the progress bar at the top.",
      zh: "在下方框内把短文滚动到底，留意顶部的进度条。",
      ja: "下の枠の短い記事を最後までスクロールして、上部の進捗バーに注目しましょう。",
    },
    peek: {
      th: "เลื่อนอ่านให้ถึงข้อสุดท้าย",
      en: "Scroll to the last tip",
      zh: "滚动到最后一条",
      ja: "最後のコツまでスクロール",
    },
    demo: "scroll",
    problem: {
      th: "หน้าจอมีพื้นที่จำกัด แต่เนื้อหามักยาวกว่านั้นเสมอ ผู้ใช้ต้องรู้ว่ายังมีอะไรอยู่ข้างล่าง และตอนนี้อ่านไปถึงไหนแล้ว",
      en: "Screens are small; content is usually longer. People need to know there’s more below — and how far through they are.",
      zh: "屏幕有限，内容通常更长。人们需要知道下面还有内容，以及自己读到了哪里。",
      ja: "画面は小さく、コンテンツはたいてい長いものです。人は「下にまだ続きがある」ことと、「今どこまで読んだか」を知る必要があります。",
    },
    how: {
      th: [
        "ผู้ใช้ให้ความสนใจกับส่วนบนของหน้ามากที่สุด เรื่องสำคัญจึงควรอยู่ด้านบน และควรมีสัญญาณบอกว่ายังมีต่อ เช่น เนื้อหาที่ถูกตัดครึ่งตรงขอบจอ",
        "แถบความคืบหน้า สารบัญ หรือปุ่มกลับขึ้นด้านบน ช่วยให้คนรู้ตำแหน่งของตัวเองในหน้ายาว ๆ",
        "อย่าแย่งการควบคุมการเลื่อนไปจากผู้ใช้ (Scrolljacking) เช่น บังคับความเร็วหรือทิศทาง เพราะทำให้คนรู้สึกว่าควบคุมอะไรไม่ได้",
      ],
      en: [
        "Attention is highest near the top, so lead with what matters — and hint that there’s more, for example content visibly cut off at the edge.",
        "Progress bars, tables of contents and “back to top” controls help people keep their place in long pages.",
        "Don’t hijack scrolling (scrolljacking) by forcing speed or direction. It takes control away from people and feels broken.",
      ],
      zh: [
        "页面顶部最受关注，所以先放最重要的内容，并暗示下面还有更多，比如让内容在屏幕边缘被明显截断。",
        "进度条、目录和“回到顶部”按钮能帮助人们在长页面中知道自己的位置。",
        "不要劫持滚动（scrolljacking），比如强行控制速度或方向。这会剥夺用户的控制感，让人觉得页面坏了。",
      ],
      ja: [
        "注目はページの上部ほど高いので、大切なことを先に置き、「まだ続きがある」と示します。たとえば画面の端でコンテンツが切れて見えるようにします。",
        "進捗バー、目次、「ページ上部へ」ボタンは、長いページで自分の位置を保つ助けになります。",
        "スクロールを乗っ取らないこと（スクロールジャッキング）。速度や方向を強制すると、操作している感覚が失われ、壊れているように感じられます。",
      ],
    },
    inPractice: {
      th: [
        "ฟีดโซเชียลที่โหลดโพสต์ใหม่ไปเรื่อย ๆ (Infinite scroll)",
        "แถบความคืบหน้าการอ่านบนเว็บข่าว",
        "แถวสินค้าที่เลื่อนในแนวนอนได้บนแอปช้อปปิ้ง",
      ],
      en: [
        "Social feeds that keep loading posts (infinite scroll)",
        "Reading-progress bars on news sites",
        "Horizontally scrolling product rows in shopping apps",
      ],
      zh: ["不断加载新内容的社交信息流（无限滚动）", "新闻网站上的阅读进度条", "购物 App 中可以横向滑动的商品列表"],
      ja: [
        "投稿を読み込み続けるソーシャルフィード（無限スクロール）",
        "ニュースサイトの読書進捗バー",
        "ショッピングアプリの横スクロールする商品の列",
      ],
    },
    mistake: {
      th: "ใช้ Infinite scroll กับหน้าที่ผู้ใช้ต้องค้นหาหรือเปรียบเทียบ เขาจะหาของที่เคยเห็นไม่เจอ และไปไม่ถึงส่วนท้ายของหน้าเลย",
      en: "Using infinite scroll where people need to find or compare things — they lose their place and can never reach the footer.",
      zh: "在需要查找或比较的页面上使用无限滚动——人们会找不到看过的东西，也永远到不了页脚。",
      ja: "探したり比べたりするページで無限スクロールを使うこと。見たものを見失い、フッターにも永遠にたどり着けません。",
    },
    takeaway: {
      th: "บอกให้รู้ว่ายังมีต่อ และบอกให้รู้ว่าอยู่ตรงไหน",
      en: "Show that there’s more — and show where they are.",
      zh: "告诉用户后面还有内容，也告诉他们自己在哪里。",
      ja: "「続きがある」ことと「今どこにいるか」を見せる。",
    },
    related: ["swipe", "feedback", "usability"],
    sources: ["nng-scrolling-attention", "nng-scrolljacking", "nng-infinite-scroll", "nng-scrollbars"],
    aliases: ["สกรอลล์", "เลื่อน", "scrolling", "infinite scroll", "スクロール", "滚动"],
  },
  {
    id: "toggle",
    term: "Toggle",
    ipa: "/ˈtɒɡ.əl/",
    localTerm: {
      th: "ทอกเกิล · สวิตช์เปิด/ปิด",
      en: "Switch",
      zh: "开关",
      ja: "トグル（スイッチ）",
    },
    categories: ["interaction", "component"],
    difficulty: 1,
    short: {
      th: "สวิตช์ที่สลับระหว่างสองสถานะ เปิดหรือปิด และมีผลทันทีที่กด",
      en: "A switch between two states — on or off — that takes effect the moment you flip it.",
      zh: "在两种状态（开或关）之间切换的开关，一拨动就立即生效。",
      ja: "オンとオフの 2 つの状態を切り替えるスイッチ。切り替えた瞬間に反映されます。",
    },
    instruction: {
      th: "เปิดและปิดโหมดเครื่องบิน สังเกตว่าทุกอย่างเปลี่ยนทันที โดยไม่ต้องกด “บันทึก”",
      en: "Turn Airplane mode on and off. Notice everything changes instantly — no “Save” needed.",
      zh: "打开再关闭飞行模式。注意所有变化都是即时的——不需要点“保存”。",
      ja: "機内モードをオン・オフしてみましょう。すべてが即座に変わり、「保存」は不要です。",
    },
    peek: {
      th: "ลองเปิด-ปิดโหมดเครื่องบิน",
      en: "Flip airplane mode on and off",
      zh: "开关一下飞行模式",
      ja: "機内モードをオン・オフして",
    },
    demo: "toggle",
    problem: {
      th: "การตั้งค่าแบบเปิด/ปิด ผู้ใช้ต้องรู้ทันทีว่าตอนนี้เปิดหรือปิดอยู่ และกดแล้วมีผลหรือยัง",
      en: "For on/off settings, people need to see the current state at a glance — and know whether their change has already been applied.",
      zh: "对于开/关类设置，人们需要一眼看出当前状态，并知道改动是否已经生效。",
      ja: "オン／オフの設定では、今の状態がひと目で分かり、変更がすでに反映されたかどうかが分かる必要があります。",
    },
    how: {
      th: [
        "Toggle ทำงานเหมือนสวิตช์ไฟจริง กดแล้วมีผลทันที จึงเหมาะกับการตั้งค่าระบบ เช่น Wi-Fi หรือการแจ้งเตือน",
        "สถานะต้องดูออกด้วยหลายสัญญาณ ไม่ใช่แค่สี เช่น ตำแหน่งของปุ่มกลม ป้ายกำกับ หรือไอคอน เพื่อให้คนที่ตาบอดสีเข้าใจได้",
        "ป้ายกำกับควรบอกสิ่งที่ถูกเปิด เช่น “การแจ้งเตือน” ลองอ่านออกเสียงแล้วต่อท้ายด้วย “เปิด/ปิด” ถ้าฟังแล้วแปลก แปลว่าป้ายยังไม่ชัด",
      ],
      en: [
        "A toggle works like a real light switch: flip it and the effect is immediate. That makes it ideal for system settings like Wi-Fi or notifications.",
        "Show the state with more than colour — the thumb’s position, a label or an icon — so people with colour-vision deficiency can read it too.",
        "Label what gets switched on, e.g. “Notifications”. Say the label aloud followed by “on/off” — if it sounds odd, rewrite it.",
      ],
      zh: [
        "开关就像真实的电灯开关：一拨就立即生效。因此非常适合 Wi-Fi、通知这类系统设置。",
        "不要只用颜色表示状态——还要用滑块位置、标签或图标，让色觉障碍的人也能看懂。",
        "标签应写明被开启的对象，例如“通知”。把标签读出来并在后面加上“开/关”，如果听起来别扭，就改写它。",
      ],
      ja: [
        "トグルは本物の電気のスイッチのように、切り替えた瞬間に効果が出ます。だから Wi-Fi や通知などのシステム設定に最適です。",
        "状態は色だけでなく、つまみの位置、ラベル、アイコンでも示します。色覚に違いのある人にも伝わるように。",
        "ラベルにはオンになるもの（例：「通知」）を書きます。ラベルの後に「オン／オフ」と付けて声に出し、不自然なら書き直しましょう。",
      ],
    },
    inPractice: {
      th: [
        "Wi-Fi, Bluetooth และโหมดเครื่องบินในการตั้งค่ามือถือ",
        "การเปิด/ปิดการแจ้งเตือนในแอปธนาคาร",
        "สวิตช์โหมดมืดบนเว็บไซต์",
      ],
      en: [
        "Wi-Fi, Bluetooth and Airplane mode in phone settings",
        "Turning banking-app notifications on or off",
        "Dark-mode switches on websites",
      ],
      zh: ["手机设置里的 Wi-Fi、蓝牙和飞行模式", "开启或关闭银行 App 的通知", "网站上的深色模式开关"],
      ja: ["スマホの設定にある Wi-Fi、Bluetooth、機内モード", "銀行アプリの通知のオン・オフ", "Web サイトのダークモード切り替え"],
    },
    mistake: {
      th: "ใส่ Toggle ไว้ในฟอร์มที่ต้องกด “บันทึก” ผู้ใช้จะสับสนว่าเปลี่ยนแล้วหรือยัง ในฟอร์มควรใช้ Checkbox แทน",
      en: "Putting toggles inside a form that needs a “Save” button. People can’t tell whether the change already happened — use a checkbox there instead.",
      zh: "把开关放进需要点“保存”的表单里。人们无法判断改动是否已经生效——表单里应该改用复选框。",
      ja: "「保存」ボタンが必要なフォームの中にトグルを置くこと。変更がもう反映されたのか分からなくなります。フォームではチェックボックスを使いましょう。",
    },
    takeaway: {
      th: "Toggle แปลว่า “มีผลทันที” ถ้ายังต้องกดบันทึก ให้ใช้อย่างอื่น",
      en: "Toggle means “now”. If it still needs saving, it’s not a toggle.",
      zh: "开关意味着“立即生效”。如果还需要保存，那就不该用开关。",
      ja: "トグルは「今すぐ」。保存が必要なら、トグルではない。",
    },
    related: ["feedback", "button", "default-state", "accessibility"],
    sources: ["nng-toggle", "apg-switch", "hig-toggles"],
    aliases: ["สวิตช์", "เปิดปิด", "ทอกเกิล", "switch", "on off", "トグル", "スイッチ", "开关"],
  },
  {
    id: "drag-and-drop",
    term: "Drag and drop",
    ipa: "/ˌdræɡ ən ˈdrɒp/",
    localTerm: {
      th: "ลากแล้ววาง",
      en: "Drag & drop, DnD",
      zh: "拖放",
      ja: "ドラッグ＆ドロップ",
    },
    categories: ["interaction"],
    difficulty: 2,
    short: {
      th: "การกดค้างที่สิ่งของบนหน้าจอ ลากไปยังตำแหน่งใหม่ แล้วปล่อย เพื่อย้ายหรือจัดลำดับ",
      en: "Pressing and holding an item, moving it to a new place and letting go — to move, reorder or upload.",
      zh: "按住一个项目，把它移动到新位置后松开——用于移动、排序或上传。",
      ja: "項目を押したまま新しい場所へ動かして離す操作。移動、並べ替え、アップロードに使います。",
    },
    instruction: {
      th: "จัดลำดับขั้นตอนการออกแบบให้ถูกต้อง ลากที่จุดจับ หรือใช้ปุ่มลูกศรก็ได้",
      en: "Put the design steps in the right order — drag by the handle, or use the arrow buttons.",
      zh: "把设计步骤排成正确顺序——拖动把手，或使用箭头按钮。",
      ja: "デザインの手順を正しい順番に並べましょう。ハンドルをドラッグするか、矢印ボタンを使います。",
    },
    peek: {
      th: "ลากเรียงขั้นตอนให้ถูกลำดับ",
      en: "Drag the steps into order",
      zh: "把步骤拖成正确顺序",
      ja: "手順をドラッグして並べ替えて",
    },
    demo: "drag-and-drop",
    problem: {
      th: "บางงานเข้าใจง่ายที่สุดเมื่อได้ “จับ” สิ่งของโดยตรง เช่น จัดลำดับรายการหรือย้ายไฟล์ แทนการพิมพ์ตัวเลขหรือเลือกจากเมนู",
      en: "Some tasks make most sense when you can grab things directly — reordering a list or moving a file — instead of typing numbers or digging through menus.",
      zh: "有些任务最直观的方式就是直接“抓住”东西——比如给列表排序或移动文件——而不是输入数字或翻找菜单。",
      ja: "リストの並べ替えやファイルの移動など、数字を入力したりメニューを探したりするより、直接「つかんで」動かすほうが分かりやすい作業があります。",
    },
    how: {
      th: [
        "Drag & drop ที่ดีต้องมีสัญญาณครบทุกช่วง: จุดจับที่บอกว่าลากได้ ของที่ “ยกขึ้น” ขณะลาก ตำแหน่งปลายทางที่ไฮไลต์ และผลลัพธ์ที่ชัดเจนเมื่อปล่อย",
        "นี่คือตัวอย่างของ Direct manipulation คือผู้ใช้กระทำกับวัตถุโดยตรงและเห็นผลทันที จึงรู้สึกเป็นธรรมชาติ",
        "แต่การลากต้องใช้มือที่มั่นคง WCAG 2.2 จึงกำหนดให้ทุกอย่างที่ทำได้ด้วยการลาก ต้องทำได้ด้วยการกดธรรมดาด้วย เช่น ปุ่มขึ้น/ลง",
      ],
      en: [
        "Good drag and drop signals every stage: a handle that says “draggable”, an item that lifts while moving, a highlighted drop target, and a clear result on release.",
        "It’s a form of direct manipulation — you act on the object itself and see the effect immediately, which feels natural.",
        "But dragging needs a steady hand. WCAG 2.2 asks that anything you can do by dragging can also be done with simple clicks, such as up/down buttons.",
      ],
      zh: [
        "好的拖放在每个阶段都有信号：表示“可拖动”的把手、移动时被“拿起”的项目、高亮的放置目标，以及松开时清晰的结果。",
        "这是一种“直接操纵”——直接作用于对象本身并立刻看到效果，所以感觉很自然。",
        "但拖动需要稳定的手。WCAG 2.2 要求凡是能通过拖动完成的操作，也必须能通过简单点击完成，例如上移/下移按钮。",
      ],
      ja: [
        "良いドラッグ＆ドロップは、すべての段階で合図を出します。「動かせる」と伝えるハンドル、移動中に持ち上がる項目、ハイライトされるドロップ先、そして離したときの明確な結果です。",
        "これは「ダイレクトマニピュレーション」の一種です。対象そのものを操作し、すぐに結果が見えるので自然に感じられます。",
        "ただしドラッグには安定した手の動きが必要です。WCAG 2.2 は、ドラッグでできることは単純なクリック（上へ／下へボタンなど）でもできるようにと求めています。",
      ],
    },
    inPractice: {
      th: [
        "ลากไฟล์ไปวางเพื่ออัปโหลดรูปหรือเอกสาร",
        "ย้ายการ์ดงานระหว่างคอลัมน์ในบอร์ดแบบ Kanban",
        "จัดเรียงแอปบนหน้าจอโฮมของมือถือ",
      ],
      en: [
        "Dropping files onto a page to upload them",
        "Moving task cards between columns on a Kanban board",
        "Rearranging apps on your phone’s home screen",
      ],
      zh: ["把文件拖到页面上进行上传", "在看板上把任务卡片移到不同的列", "在手机主屏幕上重新排列 App"],
      ja: ["ファイルをページにドロップしてアップロードする", "カンバンボードでタスクカードを別の列へ移す", "スマホのホーム画面でアプリを並べ替える"],
    },
    mistake: {
      th: "ให้การลากเป็นวิธีเดียวในการทำงาน คนที่ใช้คีย์บอร์ด มือสั่น หรือใช้มือถือบนรถที่สั่น จะทำงานนั้นไม่ได้เลย",
      en: "Making dragging the only way to do something — keyboard users, people with tremors and anyone on a bumpy commute are locked out.",
      zh: "把拖动作为完成某件事的唯一方式——键盘用户、手部震颤的人，以及在颠簸通勤路上的人都会被拒之门外。",
      ja: "ドラッグを唯一の操作方法にすること。キーボード利用者、手の震えがある人、揺れる電車の中の人は使えなくなります。",
    },
    takeaway: {
      th: "ให้การลากเป็นทางลัด ไม่ใช่ทางเดียว",
      en: "Let dragging be a shortcut, never the only way.",
      zh: "让拖动成为捷径，而不是唯一的路。",
      ja: "ドラッグは近道に。唯一の道にはしない。",
    },
    related: ["swipe", "feedback", "accessibility", "affordance"],
    sources: ["nng-drag-drop", "nng-direct-manipulation", "wcag-dragging", "hig-drag-drop"],
    aliases: ["ลากวาง", "ลาก", "drag", "drop", "dnd", "reorder", "ドラッグ", "拖放", "拖拽"],
  },
  {
    id: "swipe",
    term: "Swipe",
    ipa: "/swaɪp/",
    localTerm: {
      th: "สไวป์ · การปัดหน้าจอ",
      en: "Flick",
      zh: "滑动",
      ja: "スワイプ",
    },
    categories: ["interaction"],
    difficulty: 2,
    short: {
      th: "การปัดนิ้วบนหน้าจอสัมผัสอย่างรวดเร็วไปทางซ้าย ขวา ขึ้น หรือลง เพื่อเปลี่ยนเนื้อหาหรือสั่งงาน",
      en: "A quick finger stroke across a touch screen — left, right, up or down — to move content or trigger an action.",
      zh: "手指在触屏上快速划过——向左、右、上或下——以切换内容或触发操作。",
      ja: "タッチ画面を指でさっと払う動き（左右上下）。コンテンツを切り替えたり、操作を実行したりします。",
    },
    instruction: {
      th: "ปัด (หรือลากด้วยเมาส์) การ์ดไปทางซ้ายหรือขวา ลองปัดสั้น ๆ แล้วปล่อยด้วย หรือจะใช้ปุ่มด้านล่างแทนก็ได้",
      en: "Swipe the card left or right (or drag it with a mouse). Try a short swipe and let go, too — or use the buttons instead.",
      zh: "把卡片向左或向右滑动（也可以用鼠标拖动）。也试试只滑一点就松手——或者直接使用下方按钮。",
      ja: "カードを左右にスワイプ（マウスならドラッグ）してみましょう。少しだけ動かして離すのも試して。下のボタンでも操作できます。",
    },
    peek: {
      th: "ปัดข้อความไปทางซ้าย",
      en: "Swipe a message to the left",
      zh: "把消息向左滑",
      ja: "メッセージを左にスワイプ",
    },
    demo: "swipe",
    problem: {
      th: "บนมือถือ ปุ่มกินพื้นที่จอ Swipe ช่วยให้ทำงานที่ทำบ่อยได้เร็ว เช่น ลบอีเมลหรือดูรูปถัดไป โดยไม่ต้องมีปุ่มเต็มหน้าจอ",
      en: "On phones, buttons cost space. Swiping makes frequent actions fast — deleting an email, flicking to the next photo — without cluttering the screen.",
      zh: "在手机上，按钮会占用空间。滑动让高频操作变得很快——删除邮件、切换到下一张照片——又不会让屏幕变得拥挤。",
      ja: "スマホではボタンが場所を取ります。スワイプなら、メールの削除や次の写真への移動といったよく使う操作を、画面を散らかさずに素早く行えます。",
    },
    how: {
      th: [
        "Swipe มองไม่เห็นด้วยตา ผู้ใช้จึงต้องได้รับคำใบ้ เช่น การ์ดที่โผล่ขอบออกมาให้เห็น จุดบอกหน้า (Page dots) หรือการขยับเบา ๆ ให้ดูในครั้งแรก",
        "ควรมี “ระยะยืนยัน” ถ้าปัดไม่ถึงระยะ ของจะเด้งกลับที่เดิม ถ้าปัดถึง ระบบจึงทำงาน วิธีนี้ช่วยป้องกันการปัดโดยไม่ตั้งใจ",
        "การปัดทำได้ยากสำหรับบางคน WCAG จึงกำหนดว่าทุกอย่างที่ทำได้ด้วยการปัด ต้องมีวิธีที่ง่ายกว่าให้ทำได้ด้วย เช่น ปุ่มกด",
      ],
      en: [
        "Swipes are invisible, so people need hints: a card peeking in from the edge, page dots, or a small nudge animation the first time.",
        "Use a commit threshold: if the swipe is too short, the item springs back; past the threshold, the action happens. This prevents accidents.",
        "Swiping is hard for some people, so WCAG asks for a simple alternative — a button that does the same thing.",
      ],
      zh: [
        "滑动是看不见的，所以需要提示：从边缘露出一部分的卡片、页面圆点，或第一次时的小幅晃动动画。",
        "使用“确认阈值”：滑动距离太短，项目会弹回原处；超过阈值，操作才会执行。这样可以防止误操作。",
        "滑动对有些人来说很困难，因此 WCAG 要求提供简单的替代方式——一个能完成同样操作的按钮。",
      ],
      ja: [
        "スワイプは目に見えないので、ヒントが必要です。端から少しのぞくカード、ページドット、初回だけの小さな揺れのアニメーションなど。",
        "「確定のしきい値」を設けます。短いスワイプなら元の位置に戻り、しきい値を超えたら実行。これで誤操作を防げます。",
        "スワイプが難しい人もいます。WCAG は、同じ操作ができるボタンなどの簡単な代替手段を求めています。",
      ],
    },
    inPractice: {
      th: [
        "ปัดซ้ายเพื่อลบหรือเก็บอีเมล",
        "ปัดดูรูปถัดไปในแกลเลอรีหรือสตอรี",
        "ปัดเพื่อกดถูกใจหรือข้ามในแอปหาคู่",
      ],
      en: [
        "Swiping left to delete or archive an email",
        "Flicking through photos in a gallery or stories",
        "Swiping to like or pass in dating apps",
      ],
      zh: ["左滑删除或归档邮件", "在相册或快拍中滑动浏览照片", "在交友 App 中滑动选择喜欢或跳过"],
      ja: ["左スワイプでメールを削除・アーカイブ", "ギャラリーやストーリーズで写真を切り替える", "マッチングアプリで「いいね」や「スキップ」をする"],
    },
    mistake: {
      th: "ซ่อนการทำงานสำคัญไว้หลัง Swipe โดยไม่มีคำใบ้เลย ผู้ใช้ส่วนใหญ่จะไม่มีวันค้นพบมัน",
      en: "Hiding an important action behind a swipe with no hint — most people will simply never discover it.",
      zh: "把重要操作藏在没有任何提示的滑动手势里——大多数人永远不会发现它。",
      ja: "重要な操作をヒントのないスワイプの裏に隠すこと。ほとんどの人は気づかないままです。",
    },
    takeaway: {
      th: "Swipe ที่ดีต้องมีคำใบ้ ระยะยืนยัน และปุ่มสำรอง",
      en: "A good swipe has a hint, a threshold and a button backup.",
      zh: "好的滑动要有提示、确认阈值，以及备用按钮。",
      ja: "良いスワイプには、ヒントと、しきい値と、代わりのボタンがある。",
    },
    related: ["drag-and-drop", "scroll", "feedback", "accessibility"],
    sources: ["nng-horizontal-scroll", "hig-gestures", "wcag-pointer-gestures", "m3-inputs"],
    aliases: ["สไวป์", "ปัด", "gesture", "flick", "スワイプ", "滑动"],
  },
];
