import type { Concept } from "../types";

export const principleConcepts: Concept[] = [
  {
    id: "feedback",
    term: "Feedback",
    ipa: "/ˈfiːd.bæk/",
    localTerm: {
      th: "ฟีดแบ็ก · การตอบสนองของระบบ",
      en: "System feedback",
      zh: "反馈",
      ja: "フィードバック",
    },
    categories: ["principle"],
    difficulty: 1,
    short: {
      th: "การที่ระบบบอกผู้ใช้ว่า “ได้รับคำสั่งแล้ว” และกำลังเกิดอะไรขึ้น หลังจากผู้ใช้ทำอะไรบางอย่าง",
      en: "The interface telling people “got it” — and what’s happening — after they do something.",
      zh: "在人们做了某个操作之后，界面告诉他们“收到了”以及正在发生什么。",
      ja: "人が何かをしたあとに、画面が「受け取りました」と、いま何が起きているかを伝えること。",
    },
    instruction: {
      th: "กดส่งข้อความด้วยทั้งสองปุ่ม ปุ่มไหนทำให้คุณมั่นใจว่าข้อความถูกส่งไปแล้วจริง ๆ?",
      en: "Send the message with both buttons. Which one leaves you sure the message actually went?",
      zh: "分别用两个按钮发送消息。哪一个让你确信消息真的发出去了？",
      ja: "2 つのボタンでメッセージを送ってみましょう。本当に送れたと確信できるのはどちら？",
    },
    demo: "feedback",
    problem: {
      th: "เมื่อกดแล้วไม่มีอะไรเกิดขึ้น ผู้ใช้จะสงสัยว่าระบบค้างหรือเปล่า แล้วกดซ้ำ ซึ่งอาจทำให้สั่งซื้อหรือโอนเงินซ้ำได้",
      en: "When nothing seems to happen after a press, people wonder if it worked and press again — sometimes ordering or paying twice.",
      zh: "按下后似乎什么都没发生时，人们会怀疑是否成功并再按一次——有时就会重复下单或重复付款。",
      ja: "押しても何も起きないように見えると、人はうまくいったのか不安になり、もう一度押します。注文や支払いが二重になることもあります。",
    },
    how: {
      th: [
        "นี่คือหลักข้อแรกใน 10 Usability Heuristics ของ Jakob Nielsen คือ “Visibility of system status” ระบบต้องบอกสถานะให้ผู้ใช้รู้เสมอ ภายในเวลาที่เหมาะสม",
        "Feedback มีหลายระดับ: ทันทีที่กด (ปุ่มยุบลง) ระหว่างรอ (Spinner หรือแถบความคืบหน้า) และเมื่อเสร็จ (ข้อความยืนยันหรือเครื่องหมายถูก)",
        "เวลาสำคัญมาก: ไม่เกิน 0.1 วินาทีรู้สึกเหมือนทันที ไม่เกินราว 1 วินาทีผู้ใช้ยังไม่หลุดสมาธิ ถ้านานกว่านั้นควรแสดงความคืบหน้า",
      ],
      en: [
        "It’s the first of Jakob Nielsen’s 10 usability heuristics: visibility of system status. Always keep people informed, within a reasonable time.",
        "Feedback has layers: instant (the button presses in), while waiting (a spinner or progress bar) and when done (a confirmation or checkmark).",
        "Timing matters: under 0.1 s feels instant; up to about 1 s keeps people’s flow of thought; anything longer deserves a progress indicator.",
      ],
      zh: [
        "这是雅各布·尼尔森 10 条可用性原则中的第一条：系统状态可见。要在合理的时间内，始终让人们了解正在发生什么。",
        "反馈有不同层次：即时（按钮被按下）、等待中（加载动画或进度条）和完成时（确认信息或对勾）。",
        "时间很关键：0.1 秒内感觉是即时的；约 1 秒内人们的思路不会中断；更长的话就应该显示进度。",
      ],
      ja: [
        "ヤコブ・ニールセンの「10 のユーザビリティ原則」の第 1 項、「システム状態の可視化」です。妥当な時間内に、常に状況を知らせます。",
        "フィードバックには段階があります。押した瞬間（ボタンがへこむ）、待っている間（スピナーや進捗バー）、完了時（確認メッセージやチェックマーク）。",
        "時間が大切です。0.1 秒以内なら即座に感じ、約 1 秒までなら思考の流れが途切れません。それ以上かかるなら進捗を表示しましょう。",
      ],
    },
    inPractice: {
      th: [
        "สถานะ “อ่านแล้ว” ในแอปแชต",
        "แถบความคืบหน้าระหว่างอัปโหลดรูป",
        "การสั่นเบา ๆ เมื่อสแกนจ่ายเงินผ่าน QR สำเร็จ",
      ],
      en: [
        "“Read” indicators in messaging apps",
        "Progress bars while photos upload",
        "A gentle haptic buzz when a QR payment succeeds",
      ],
      zh: ["聊天 App 中的“已读”标记", "上传照片时的进度条", "扫码支付成功时轻微的振动反馈"],
      ja: ["メッセージアプリの「既読」表示", "写真をアップロードするときの進捗バー", "QR 決済が成功したときの軽い振動"],
    },
    mistake: {
      th: "ทำงานสำเร็จแบบเงียบ ๆ ผู้ใช้จะกดซ้ำ หรือออกจากหน้าไปโดยไม่รู้ว่างานเสร็จหรือยัง",
      en: "Succeeding silently. People press again, or leave without knowing whether it worked.",
      zh: "默默地成功，什么都不显示。人们会再按一次，或者在不知道是否成功的情况下离开。",
      ja: "成功を黙ったままにすること。人はもう一度押すか、うまくいったか分からないまま去ってしまいます。",
    },
    takeaway: {
      th: "ทุกการกระทำต้องมีเสียงตอบรับ",
      en: "Every action deserves an answer.",
      zh: "每一个操作都值得一个回应。",
      ja: "すべての操作には、応答があるべき。",
    },
    related: ["loading-state", "success-state", "error-state", "click"],
    sources: ["nng-heuristics", "nng-visibility", "nng-response-times", "hig-feedback"],
    aliases: ["ฟีดแบ็ก", "การตอบสนอง", "response", "visibility of system status", "フィードバック", "反馈"],
  },
  {
    id: "affordance",
    term: "Affordance",
    ipa: "/əˈfɔː.dəns/",
    localTerm: {
      th: "อะฟอร์แดนซ์ · สิ่งที่บอกว่าใช้งานได้อย่างไร",
      en: "Perceived affordance, signifier",
      zh: "示能（可供性）",
      ja: "アフォーダンス",
    },
    categories: ["principle"],
    difficulty: 2,
    short: {
      th: "สัญญาณที่บอกผู้ใช้ว่าสิ่งนั้น “ใช้งานได้อย่างไร” เช่น ปุ่มที่ดูนูนชวนให้กด หรือแถบเลื่อนที่ชวนให้ลาก",
      en: "The cues that tell people how something can be used — a raised button invites a press, a slider invites a drag.",
      zh: "告诉人们某物可以如何使用的线索——凸起的按钮邀请你按，滑块邀请你拖。",
      ja: "それがどう使えるかを人に伝える手がかり。盛り上がったボタンは押したくなり、スライダーはドラッグしたくなります。",
    },
    instruction: {
      th: "ลองเดาว่าองค์ประกอบไหนคลิกได้บ้าง แตะสิ่งที่คุณคิดว่ากดได้ แล้วกด “เฉลย”",
      en: "Guess which elements are clickable. Tap the ones you think you can press, then reveal the answer.",
      zh: "猜猜哪些元素可以点击。点一下你认为能按的，然后揭晓答案。",
      ja: "どの要素がクリックできるか当ててみましょう。押せると思うものをタップしてから、答えを見ます。",
    },
    demo: "affordance",
    problem: {
      th: "ถ้าผู้ใช้มองไม่ออกว่าอะไรกดได้ เขาจะลังเล กดผิด หรือพลาดฟีเจอร์ที่มีอยู่ไปเลย",
      en: "If people can’t tell what’s interactive, they hesitate, click the wrong thing, or miss features entirely.",
      zh: "如果人们看不出什么是可以交互的，他们会犹豫、点错，甚至完全错过某些功能。",
      ja: "何が操作できるのか分からないと、人は迷い、間違ったものを押し、機能そのものを見逃してしまいます。",
    },
    how: {
      th: [
        "คำนี้มาจากนักจิตวิทยา James J. Gibson และ Don Norman นำมาใช้ในงานออกแบบ บนหน้าจอ สิ่งที่สำคัญคือ Affordance ที่ “ผู้ใช้รับรู้ได้” ว่าทำอะไรได้",
        "ต่อมา Norman แนะนำคำว่า Signifier สำหรับสัญญาณที่มองเห็นได้ เช่น ลิงก์ที่ขีดเส้นใต้ ปุ่มที่มีรูปทรงและพื้นหลัง หรือจุดจับสำหรับลาก",
        "ดีไซน์แบนราบสุดขั้วที่ตัดสัญญาณเหล่านี้ออกหมด ทำให้คนต้องเดาและใช้เวลานานขึ้น ความเรียบง่ายจึงต้องไม่แลกกับความชัดเจน",
      ],
      en: [
        "The term comes from psychologist James J. Gibson; Don Norman brought it into design. On screens, what matters is the perceived affordance — what people believe they can do.",
        "Norman later suggested “signifiers” for the visible cues: underlined links, buttons with shape and fill, grab handles for dragging.",
        "Ultra-flat designs that strip these cues away make people guess and slow down. Minimalism must never cost clarity.",
      ],
      zh: [
        "这个词来自心理学家詹姆斯·吉布森，唐·诺曼把它引入设计领域。在屏幕上，重要的是“被感知的”示能——人们以为自己能做什么。",
        "诺曼后来建议用“意符”（signifier）指代可见的线索：带下划线的链接、有形状和填充色的按钮、用于拖动的把手。",
        "去掉所有线索的极端扁平设计会让人去猜，并且变慢。极简绝不能以牺牲清晰为代价。",
      ],
      ja: [
        "この言葉は心理学者ジェームズ・J・ギブソンに由来し、ドン・ノーマンがデザインの世界に持ち込みました。画面上で大切なのは「知覚されたアフォーダンス」、つまり人が「できる」と思えることです。",
        "ノーマンは後に、目に見える手がかりを「シグニファイア」と呼ぶことを提案しました。下線付きのリンク、形と塗りのあるボタン、ドラッグ用のハンドルなどです。",
        "手がかりをすべて取り除いた極端なフラットデザインは、人に推測を強い、操作を遅くします。ミニマルさと引き換えに分かりやすさを失ってはいけません。",
      ],
    },
    inPractice: {
      th: [
        "ปุ่มที่มีพื้นหลังและมุมโค้ง ดูออกทันทีว่ากดได้",
        "ลิงก์สีน้ำเงินขีดเส้นใต้ที่คนคุ้นเคยมาหลายสิบปี",
        "จุดจับ (⋮⋮) บนการ์ดที่บอกว่าลากได้",
      ],
      en: [
        "Buttons with a fill and rounded corners that look pressable",
        "Blue, underlined links people have recognised for decades",
        "Grip handles (⋮⋮) on cards that say “drag me”",
      ],
      zh: ["有填充色和圆角、看起来就能按的按钮", "几十年来人们都认得的蓝色下划线链接", "卡片上表示“可以拖动”的把手（⋮⋮）"],
      ja: ["塗りと角丸があり、押せそうに見えるボタン", "何十年も親しまれてきた青い下線付きリンク", "「ドラッグできる」と伝えるカード上のハンドル（⋮⋮）"],
    },
    mistake: {
      th: "ทำข้อความธรรมดาให้ดูเหมือนลิงก์ หรือทำปุ่มให้ดูเหมือนข้อความ ผู้ใช้จะกดสิ่งที่กดไม่ได้ และมองข้ามสิ่งที่กดได้",
      en: "Styling plain text like a link, or a button like plain text. People click what isn’t clickable and skip what is.",
      zh: "把普通文字做得像链接，或把按钮做得像普通文字。人们会去点不能点的，却忽略能点的。",
      ja: "ただのテキストをリンクのように、ボタンをただのテキストのように見せること。押せないものを押し、押せるものを見逃してしまいます。",
    },
    takeaway: {
      th: "ถ้าต้องอธิบายว่ากดตรงไหน แปลว่าดีไซน์ยังพูดไม่ชัด",
      en: "If you have to explain where to click, the design isn’t speaking clearly yet.",
      zh: "如果还需要解释该点哪里，说明设计还不够清晰。",
      ja: "どこを押すか説明が必要なら、デザインはまだ十分に語れていない。",
    },
    related: ["button", "hover", "feedback", "default-state"],
    sources: ["norman-signifiers", "norman-affordances", "nng-clickable", "nng-flat-ui", "laws-jakob"],
    aliases: ["อะฟอร์แดนซ์", "ซิกนิฟายเออร์", "signifier", "affordances", "アフォーダンス", "シグニファイア", "示能", "可供性", "意符"],
  },
  {
    id: "usability",
    term: "Usability",
    ipa: "/ˌjuː.zəˈbɪl.ə.ti/",
    localTerm: {
      th: "ยูสซาบิลิตี้ · ความง่ายในการใช้งาน",
      en: "Ease of use",
      zh: "可用性（易用性）",
      ja: "ユーザビリティ",
    },
    categories: ["principle"],
    difficulty: 1,
    short: {
      th: "ความง่ายที่ผู้ใช้จะทำสิ่งที่ต้องการได้สำเร็จ อย่างถูกต้อง รวดเร็ว และพึงพอใจ",
      en: "How easily people can achieve what they came to do — accurately, quickly and without frustration.",
      zh: "人们能否轻松地完成想做的事——准确、快速、且不受挫。",
      ja: "人が目的を、正確に、素早く、ストレスなく達成できる度合い。",
    },
    instruction: {
      th: "ภารกิจ: หาหน้า “เปลี่ยนรหัสผ่าน” ในเมนูทั้งสองแบบ แล้วเทียบเวลาที่ใช้",
      en: "Your task: find “Change password” in both menus and compare your times.",
      zh: "任务：在两个菜单中分别找到“修改密码”，比较各自用了多少时间。",
      ja: "タスク：2 つのメニューで「パスワードを変更」を探し、かかった時間を比べましょう。",
    },
    demo: "usability",
    problem: {
      th: "ผลิตภัณฑ์ที่สวยแต่ใช้ยาก ทำให้คนทำงานไม่สำเร็จ ต้องโทรถามคอลเซ็นเตอร์ หรือเลิกใช้แล้วไปหาคู่แข่ง",
      en: "A beautiful product that’s hard to use leaves tasks unfinished, floods the call centre and sends people to competitors.",
      zh: "外观漂亮却难用的产品，会让任务无法完成、客服电话爆满，并把用户推向竞争对手。",
      ja: "見た目が美しくても使いにくい製品は、タスクを未完了のままにし、コールセンターを混雑させ、人を競合へと向かわせます。",
    },
    how: {
      th: [
        "มาตรฐาน ISO 9241-11 นิยาม Usability ด้วย 3 ส่วน: ประสิทธิผล (ทำสำเร็จไหม) ประสิทธิภาพ (ใช้แรงและเวลามากแค่ไหน) และความพึงพอใจ (รู้สึกอย่างไร)",
        "Jakob Nielsen เสริมว่าต้องเรียนรู้ง่าย จำได้ง่ายเมื่อกลับมาใช้ใหม่ และเกิดข้อผิดพลาดน้อยหรือแก้ไขได้ง่าย",
        "วิธีวัดที่ดีที่สุดคือดูคนจริงใช้งานจริง ให้ทำภารกิจแล้วสังเกตว่าเขาติดตรงไหน ไม่ใช่ถามว่าเขา “ชอบ” หรือเปล่า",
      ],
      en: [
        "ISO 9241-11 defines usability with three parts: effectiveness (did they succeed?), efficiency (how much effort did it take?) and satisfaction (how did it feel?).",
        "Jakob Nielsen adds learnability, memorability when people come back, and few errors that are easy to recover from.",
        "The best way to measure it is to watch real people do real tasks and note where they struggle — not to ask whether they “like” it.",
      ],
      zh: [
        "ISO 9241-11 用三部分定义可用性：有效性（是否完成？）、效率（花了多少力气？）和满意度（感受如何？）。",
        "雅各布·尼尔森补充了易学性、再次使用时的易记性，以及错误少且容易恢复。",
        "最好的衡量方式是观察真实的人完成真实的任务，记录他们在哪里卡住——而不是问他们“喜不喜欢”。",
      ],
      ja: [
        "ISO 9241-11 はユーザビリティを 3 つの要素で定義しています。有効さ（達成できたか）、効率（どれだけ労力がかかったか）、満足度（どう感じたか）。",
        "ヤコブ・ニールセンは、学びやすさ、再訪時の覚えやすさ、エラーが少なく回復しやすいことを加えています。",
        "測る最良の方法は、実際の人に実際のタスクをしてもらい、どこでつまずくかを観察すること。「好きか」を聞くことではありません。",
      ],
    },
    inPractice: {
      th: [
        "แอปธนาคารที่โอนเงินเสร็จได้ในไม่กี่ขั้นตอน",
        "ตู้จำหน่ายตั๋วที่ใช้ถูกตั้งแต่ครั้งแรก",
        "เว็บราชการที่ยื่นคำร้องเสร็จได้โดยไม่ต้องโทรถามใคร",
      ],
      en: [
        "Banking apps that complete a transfer in a few steps",
        "Ticket machines you can use correctly the first time",
        "Government sites where you finish an application without calling anyone",
      ],
      zh: ["几步就能完成转账的银行 App", "第一次就能正确使用的售票机", "无需打电话询问就能完成申请的政务网站"],
      ja: ["数ステップで振込が終わる銀行アプリ", "初めてでも正しく使える券売機", "誰にも電話せずに申請を終えられる行政サイト"],
    },
    mistake: {
      th: "คิดว่า “ฉันใช้ได้ คนอื่นก็ต้องใช้ได้” คนออกแบบรู้จักผลิตภัณฑ์ดีเกินไป จึงมองไม่เห็นจุดที่คนใหม่ติดขัด",
      en: "Thinking “I can use it, so everyone can.” Designers know their product too well to see where newcomers stumble.",
      zh: "认为“我会用，所以大家都会用”。设计者太熟悉自己的产品，以至于看不到新手会在哪里卡住。",
      ja: "「自分が使えるのだから、みんなも使える」と考えること。作り手は製品を知りすぎていて、初めての人がつまずく場所が見えません。",
    },
    takeaway: {
      th: "Usability ไม่ได้วัดจากความเห็น แต่วัดจากสิ่งที่คนทำได้จริง",
      en: "Usability is measured by what people can do, not what they say.",
      zh: "可用性看的是人们能做到什么，而不是他们怎么说。",
      ja: "ユーザビリティは、人の意見ではなく、実際にできたことで測る。",
    },
    related: ["accessibility", "feedback", "affordance"],
    sources: ["nng-usability-101", "iso-9241-11", "nng-usability-testing", "nng-five-users"],
    aliases: ["ยูสซาบิลิตี้", "ใช้ง่าย", "ease of use", "ユーザビリティ", "使いやすさ", "可用性", "易用性"],
  },
  {
    id: "accessibility",
    term: "Accessibility",
    ipa: "/əkˌses.əˈbɪl.ə.ti/",
    localTerm: {
      th: "แอคเซสซิบิลิตี้ · การออกแบบให้ทุกคนเข้าถึงได้",
      en: "a11y",
      zh: "无障碍（可访问性）",
      ja: "アクセシビリティ",
    },
    categories: ["principle"],
    difficulty: 2,
    short: {
      th: "การออกแบบให้ทุกคนใช้งานได้ รวมถึงผู้พิการ ผู้สูงอายุ และคนที่อยู่ในสถานการณ์ที่มีข้อจำกัด",
      en: "Designing so everyone can use it — including disabled people, older people and anyone in a limiting situation.",
      zh: "让每个人都能使用的设计——包括残障人士、老年人，以及处于受限情境中的任何人。",
      ja: "障害のある人、高齢の人、制約のある状況にいる人を含め、誰もが使えるように設計すること。",
    },
    instruction: {
      th: "เปิดตัวจำลองทีละแบบ (มองไม่ชัด ตาบอดสี คอนทราสต์ต่ำ) แล้วลองดูว่ายังใช้การ์ดสั่งอาหารได้ไหม",
      en: "Turn on each simulation — blurred vision, colour blindness, low contrast — and see whether you can still use the order card.",
      zh: "逐一打开模拟效果——视力模糊、色盲、低对比度——看看你还能不能使用这张点餐卡片。",
      ja: "シミュレーション（視界のぼやけ、色覚の違い、低コントラスト）を 1 つずつオンにして、注文カードがまだ使えるか試してみましょう。",
    },
    demo: "accessibility",
    problem: {
      th: "ผู้คนกว่าพันล้านคนทั่วโลกมีความพิการ และทุกคนล้วนเคยมีข้อจำกัดชั่วคราว เช่น แขนเจ็บ อยู่กลางแดดจ้า หรืออุ้มเด็กไว้หนึ่งมือ",
      en: "Over a billion people live with a disability — and everyone has temporary limits: an injured arm, bright sunlight, a baby in one hand.",
      zh: "全球有超过十亿人身患残障——而每个人都会遇到暂时的限制：手臂受伤、强烈阳光、一只手抱着孩子。",
      ja: "世界で 10 億人以上が障害とともに暮らしています。そして誰にでも一時的な制約があります。腕のけが、強い日差し、片手で赤ちゃんを抱いているとき。",
    },
    how: {
      th: [
        "WCAG แบ่งหลักการเป็น 4 ข้อ (POUR): รับรู้ได้ (Perceivable) ใช้งานได้ (Operable) เข้าใจได้ (Understandable) และทำงานกับเทคโนโลยีที่หลากหลายได้ (Robust)",
        "เรื่องพื้นฐานที่ทำได้ทันที: คอนทราสต์ตัวอักษรอย่างน้อย 4.5:1 ใช้งานได้ด้วยคีย์บอร์ดทั้งหมด มองเห็นโฟกัสชัด ไม่สื่อความหมายด้วยสีอย่างเดียว และมีข้อความแทนรูปภาพ",
        "แนวคิด Persona spectrum ของ Microsoft ชี้ว่า เมื่อออกแบบเพื่อคนที่มีข้อจำกัดถาวร คนที่มีข้อจำกัดชั่วคราวหรือตามสถานการณ์ก็ได้ประโยชน์ไปด้วย",
      ],
      en: [
        "WCAG organises accessibility into four principles (POUR): Perceivable, Operable, Understandable and Robust.",
        "Basics you can do today: text contrast of at least 4.5:1, full keyboard support, a visible focus, never colour alone, and text alternatives for images.",
        "Microsoft’s persona spectrum shows that designing for a permanent limitation also helps people with temporary or situational ones.",
      ],
      zh: [
        "WCAG 把无障碍归纳为四大原则（POUR）：可感知、可操作、可理解、健壮。",
        "今天就能做的基本功：文字对比度至少 4.5:1、完整支持键盘操作、焦点清晰可见、不只依赖颜色传达信息，以及为图片提供替代文字。",
        "微软的“人物光谱”（persona spectrum）表明：为永久性限制而设计，同样会惠及有暂时性或情境性限制的人。",
      ],
      ja: [
        "WCAG はアクセシビリティを 4 つの原則（POUR）にまとめています。知覚可能、操作可能、理解可能、堅牢。",
        "今日からできる基本：文字のコントラスト比 4.5:1 以上、キーボードだけで操作できること、フォーカスが見えること、色だけに頼らないこと、画像の代替テキスト。",
        "マイクロソフトの「ペルソナ・スペクトラム」は、永続的な制約のために設計すると、一時的・状況的な制約がある人にも役立つことを示しています。",
      ],
    },
    inPractice: {
      th: [
        "คำบรรยายใต้วิดีโอที่ช่วยทั้งคนหูหนวกและคนที่ดูในที่ที่ต้องเงียบ",
        "ทางลาดสำหรับรถเข็นที่ช่วยคนลากกระเป๋าเดินทางด้วย",
        "ขนาดตัวอักษรที่ปรับได้ในการตั้งค่ามือถือ",
      ],
      en: [
        "Captions that help deaf viewers and anyone watching on a silent train",
        "Kerb ramps built for wheelchairs that help everyone with luggage",
        "Adjustable text size in phone settings",
      ],
      zh: ["既帮助听障观众、也方便在安静车厢里观看的字幕", "为轮椅修建、却方便所有拖行李的人的缘石坡道", "手机设置中可以调节的字体大小"],
      ja: ["耳の聞こえない人にも、静かな電車で見る人にも役立つ字幕", "車椅子のために作られ、スーツケースを引く人も助かる段差スロープ", "スマホの設定で変えられる文字サイズ"],
    },
    mistake: {
      th: "คิดว่า Accessibility เป็นงานเสริมที่ค่อยทำทีหลัง การแก้ตอนท้ายแพงกว่าการออกแบบให้ถูกตั้งแต่ต้องหลายเท่า",
      en: "Treating accessibility as an extra for later. Retrofitting costs far more than designing it in from the start.",
      zh: "把无障碍当作以后再做的附加项。事后补救的成本远高于一开始就把它设计进去。",
      ja: "アクセシビリティを後回しの「おまけ」と考えること。後から直すのは、最初から組み込むよりはるかに高くつきます。",
    },
    takeaway: {
      th: "ออกแบบเพื่อคนที่อยู่ขอบ แล้วคนตรงกลางจะได้ประโยชน์ด้วย",
      en: "Design for the edges, and the middle benefits too.",
      zh: "为边缘而设计，中间的人也会受益。",
      ja: "端にいる人のために設計すれば、真ん中の人も恩恵を受ける。",
    },
    related: ["usability", "focus-state", "drag-and-drop", "tooltip"],
    sources: ["wai-intro", "wai-principles", "wcag-contrast", "ms-inclusive", "govuk-accessible"],
    aliases: ["แอคเซสซิบิลิตี้", "การเข้าถึง", "a11y", "wcag", "inclusive", "アクセシビリティ", "无障碍", "可访问性"],
  },
];
