import type { Concept } from "../types";

export const stateConcepts: Concept[] = [
  {
    id: "default-state",
    term: "Default state",
    ipa: "/dɪˈfɒlt steɪt/",
    localTerm: {
      th: "สถานะปกติ",
      en: "Enabled or resting state",
      zh: "默认状态",
      ja: "デフォルト状態",
    },
    categories: ["state"],
    difficulty: 1,
    short: {
      th: "หน้าตาขององค์ประกอบตอนที่ยังไม่มีใครแตะต้อง ซึ่งเป็นสถานะที่ผู้ใช้เห็นบ่อยที่สุด",
      en: "How an element looks when nobody is touching it — the state people see most often.",
      zh: "元素在没有人操作时的样子——也是人们最常看到的状态。",
      ja: "誰も触れていないときの要素の見た目。人が最もよく目にする状態です。",
    },
    instruction: {
      th: "อย่าเพิ่งแตะอะไร ดูแค่สถานะปกติ แล้วเลือกปุ่มที่ดูกดได้ชัดที่สุด",
      en: "Don’t touch anything yet. Looking only at the default state, pick the button that looks most clickable.",
      zh: "先什么都别碰。只看默认状态，选出看起来最像可以点击的按钮。",
      ja: "まだ何も触らずに、デフォルト状態だけを見て、いちばん押せそうなボタンを選んでみましょう。",
    },
    demo: "default-state",
    problem: {
      th: "ผู้ใช้ตัดสินใจส่วนใหญ่จากสิ่งที่เห็นก่อนแตะ ถ้าสถานะปกติไม่บอกว่าใช้งานได้ ก็จะไม่มีใครแตะเพื่อไปเห็น Hover หรือ Feedback เลย",
      en: "Most decisions happen before any touch. If the default state doesn’t look usable, no one will ever reach the hover or the feedback.",
      zh: "大多数决定发生在触碰之前。如果默认状态看起来不可用，就没人会去触发悬停或看到反馈。",
      ja: "ほとんどの判断は触れる前に行われます。デフォルト状態が使えそうに見えなければ、誰もホバーやフィードバックまでたどり着きません。",
    },
    how: {
      th: [
        "สถานะปกติต้อง “พูด” ได้ด้วยตัวเอง รูปร่าง สี และข้อความต้องบอกว่าองค์ประกอบนี้คืออะไรและทำอะไร",
        "สถานะอื่นทั้งหมด (Hover, Active, Focus, Disabled) ออกแบบโดยเปลี่ยนจากสถานะปกติ จึงควรทำสถานะนี้ให้แข็งแรงก่อน",
        "ความสม่ำเสมอสำคัญ ปุ่มชนิดเดียวกันควรหน้าตาเหมือนกันทุกหน้า ผู้ใช้จะได้เรียนรู้ครั้งเดียวแล้วใช้ได้ทุกที่",
      ],
      en: [
        "The default state has to speak for itself: shape, colour and label should say what the element is and does.",
        "Every other state — hover, active, focus, disabled — is designed as a change from the default, so get this one strong first.",
        "Consistency matters: the same kind of button should look the same on every page, so people learn it once and use it everywhere.",
      ],
      zh: [
        "默认状态必须能“自己说话”：形状、颜色和文字要说明这个元素是什么、能做什么。",
        "其他所有状态——悬停、按下、焦点、禁用——都是在默认状态基础上的变化，所以要先把默认状态做扎实。",
        "一致性很重要：同一类按钮在每个页面都应该长得一样，这样人们学一次就能处处使用。",
      ],
      ja: [
        "デフォルト状態は、それだけで語れる必要があります。形、色、ラベルで、それが何で何をするのかを伝えます。",
        "ホバー、アクティブ、フォーカス、無効など他のすべての状態は、デフォルトからの変化として設計されます。まずはここを強く。",
        "一貫性が大切です。同じ種類のボタンはどのページでも同じ見た目に。一度覚えれば、どこでも使えます。",
      ],
    },
    inPractice: {
      th: [
        "ปุ่มหลักสีเข้มที่โดดเด่นในหน้าชำระเงิน",
        "ช่องกรอกข้อมูลที่มีกรอบชัดเจนแม้ยังว่างอยู่",
        "แถบแท็บที่บอกชัดว่าตอนนี้เลือกแท็บไหนอยู่",
      ],
      en: [
        "A solid primary button that stands out on a checkout page",
        "Input fields with a clear border even when empty",
        "Tab bars that make the selected tab obvious",
      ],
      zh: ["在结账页面中格外醒目的实心主按钮", "即使为空也有清晰边框的输入框", "清楚标明当前选中项的标签栏"],
      ja: ["購入ページで目立つ塗りつぶしのメインボタン", "空のときでも枠がはっきりした入力欄", "選択中のタブがひと目で分かるタブバー"],
    },
    mistake: {
      th: "ทำปุ่มเป็นสีเทาอ่อนเพื่อความ “มินิมอล” จนดูเหมือนปุ่มที่ใช้งานไม่ได้",
      en: "Making buttons pale grey for a “minimal” look — until they look disabled.",
      zh: "为了“极简”把按钮做成浅灰色——结果看起来像是被禁用了。",
      ja: "「ミニマル」に見せようとボタンを薄いグレーにして、無効状態のように見せてしまうこと。",
    },
    takeaway: {
      th: "สถานะปกติคือคำเชิญ ต้องชัดตั้งแต่ก่อนผู้ใช้จะแตะ",
      en: "The default state is the invitation. It must be clear before anyone touches it.",
      zh: "默认状态就是邀请函，必须在任何人触碰前就清楚明了。",
      ja: "デフォルト状態は招待状。触れる前から分かりやすくなければならない。",
    },
    related: ["affordance", "hover", "active-state", "disabled-state"],
    sources: ["nng-button-states", "m3-states", "nng-flat-ui"],
    aliases: ["สถานะปกติ", "default", "enabled", "rest", "デフォルト", "默认"],
  },
  {
    id: "active-state",
    term: "Active state",
    ipa: "/ˈæk.tɪv steɪt/",
    localTerm: {
      th: "สถานะขณะถูกกด",
      en: "Pressed state",
      zh: "按下状态（激活状态）",
      ja: "アクティブ状態（押下状態）",
    },
    categories: ["state"],
    difficulty: 1,
    short: {
      th: "หน้าตาขององค์ประกอบในเสี้ยววินาทีที่ถูกกดอยู่ เพื่อยืนยันว่าระบบรับรู้การกดแล้ว",
      en: "How an element looks during the split second it’s being pressed — proof that the press registered.",
      zh: "元素在被按下的那一瞬间的样子——证明按压已被识别。",
      ja: "押されている一瞬の要素の見た目。押したことが伝わった証拠です。",
    },
    instruction: {
      th: "กดปุ่มทั้งสองค้างไว้แล้วปล่อย ปุ่มไหนให้ความรู้สึกเหมือนกดปุ่มจริง?",
      en: "Press and hold each button, then release. Which one feels like pressing a real button?",
      zh: "按住每个按钮再松开。哪一个感觉像在按一个真实的按钮？",
      ja: "それぞれのボタンを長押ししてから離してみましょう。本物のボタンを押した感覚があるのはどちら？",
    },
    demo: "active-state",
    problem: {
      th: "บนจอสัมผัส นิ้วจะบังปุ่มขณะกด ผู้ใช้จึงต้องการสัญญาณที่เร็วและชัดว่ากดโดนแล้ว ไม่อย่างนั้นจะกดซ้ำ",
      en: "On touch screens your finger covers the button, so people need a fast, clear signal that the press landed — or they’ll press again.",
      zh: "在触屏上，手指会挡住按钮，所以人们需要一个快速而清晰的信号表明按中了——否则就会再按一次。",
      ja: "タッチ画面では指がボタンを隠してしまうので、押せたことを素早くはっきり伝える合図が必要です。なければ、もう一度押してしまいます。",
    },
    how: {
      th: [
        "สถานะขณะกดควรเปลี่ยนทันที เช่น ปุ่มยุบลงเล็กน้อย สีเข้มขึ้น หรือเงาหายไป เลียนแบบปุ่มในโลกจริง",
        "สถานะนี้อยู่แค่ชั่วพริบตา จึงต้องชัดพอที่จะรู้สึกได้โดยไม่ต้องจ้องมอง แต่ต้องไม่นานจนทำให้รู้สึกว่าระบบช้า",
        "บางแพลตฟอร์มเพิ่มระลอกคลื่น (Ripple) หรือการสั่นเบา ๆ (Haptic) เป็นสัญญาณเสริม",
      ],
      en: [
        "The pressed state should appear instantly: a slight shrink, a deeper colour, a shadow that disappears — just like a physical button.",
        "It lasts a moment, so it must be noticeable without staring — but never so long that the interface feels sluggish.",
        "Some platforms add a ripple or a light haptic tap as an extra signal.",
      ],
      zh: [
        "按下状态应该立即出现：轻微缩小、颜色加深、阴影消失——就像实体按钮一样。",
        "它只持续一瞬间，所以必须不用盯着看也能察觉——但又不能太长，让界面显得迟钝。",
        "有些平台会加上涟漪效果或轻微振动作为额外信号。",
      ],
      ja: [
        "押下状態は即座に表示します。少し縮む、色が濃くなる、影が消える。物理的なボタンと同じです。",
        "一瞬しか続かないので、じっと見なくても気づける必要があります。ただし長すぎると動作が重く感じられます。",
        "プラットフォームによっては、波紋（リップル）や軽い振動を追加の合図として使います。",
      ],
    },
    inPractice: {
      th: [
        "ปุ่มบนแป้นพิมพ์มือถือที่ขยายขึ้นเมื่อกด",
        "ปุ่มในแอปที่ยุบลงเล็กน้อยใต้ปลายนิ้ว",
        "เอฟเฟกต์ระลอกคลื่นในแอป Android",
      ],
      en: [
        "Phone keyboard keys that pop up as you press them",
        "App buttons that shrink slightly under your finger",
        "The ripple effect in Android apps",
      ],
      zh: ["按下时会弹出放大的手机键盘按键", "在手指下轻微缩小的 App 按钮", "Android App 中的涟漪效果"],
      ja: ["押すとポップアップするスマホのキーボード", "指の下で少し縮むアプリのボタン", "Android アプリのリップルエフェクト"],
    },
    mistake: {
      th: "ลืมออกแบบสถานะขณะกด ทำให้ปุ่มดูเหมือนรูปภาพแบน ๆ ที่ไม่ตอบสนองอะไรเลย",
      en: "Forgetting the pressed state entirely, so buttons feel like flat pictures that ignore you.",
      zh: "完全忘了按下状态，让按钮感觉像一张对你毫无反应的平面图片。",
      ja: "押下状態を作り忘れて、ボタンが反応しない平らな絵のように感じられること。",
    },
    takeaway: {
      th: "ทุกการกดต้องรู้สึกได้ภายในเสี้ยววินาที",
      en: "Every press should be felt within a fraction of a second.",
      zh: "每一次按压都应在瞬间被感知。",
      ja: "どの押下も、一瞬のうちに感じられるように。",
    },
    related: ["click", "feedback", "button", "default-state"],
    sources: ["nng-button-states", "m3-states", "nng-response-times"],
    aliases: ["สถานะกด", "กดค้าง", "pressed", "active", "アクティブ", "押下", "按下"],
  },
  {
    id: "focus-state",
    term: "Focus state",
    ipa: "/ˈfəʊ.kəs steɪt/",
    localTerm: {
      th: "สถานะโฟกัส",
      en: "Focus ring, focus indicator",
      zh: "焦点状态",
      ja: "フォーカス状態",
    },
    categories: ["state"],
    difficulty: 2,
    short: {
      th: "กรอบหรือไฮไลต์ที่บอกว่าตอนนี้คีย์บอร์ดอยู่ที่องค์ประกอบไหน เหมือนเคอร์เซอร์ของคนที่ไม่ได้ใช้เมาส์",
      en: "The outline that shows which element the keyboard is on — the cursor for people who don’t use a mouse.",
      zh: "显示键盘当前位于哪个元素上的轮廓——对不使用鼠标的人来说，它就是光标。",
      ja: "キーボードがいまどの要素にあるかを示す枠。マウスを使わない人にとってのカーソルです。",
    },
    instruction: {
      th: "คลิกในกรอบตัวอย่าง แล้วกดปุ่ม Tab สักสองสามครั้ง จากนั้นเปิด “ซ่อนกรอบโฟกัส” แล้วกด Tab อีกครั้ง คุณยังรู้ไหมว่าตัวเองอยู่ตรงไหน?",
      en: "Click inside the example and press Tab a few times. Then switch on “Hide focus ring” and Tab again — can you still tell where you are?",
      zh: "点击示例区域，然后按几次 Tab 键。再打开“隐藏焦点框”并继续按 Tab——你还知道自己在哪里吗？",
      ja: "例の中をクリックして、Tab キーを何回か押してみましょう。次に「フォーカス枠を隠す」をオンにしてもう一度 Tab。いまどこにいるか分かりますか？",
    },
    demo: "focus-state",
    problem: {
      th: "หลายคนใช้งานด้วยคีย์บอร์ด เช่น ผู้ที่มีข้อจำกัดด้านการเคลื่อนไหว ผู้ใช้โปรแกรมอ่านหน้าจอ หรือคนที่อยากทำงานเร็ว ถ้าไม่เห็นโฟกัส ก็เหมือนใช้เมาส์ที่มองไม่เห็นเคอร์เซอร์",
      en: "Many people navigate by keyboard — people with motor impairments, screen-reader users, power users. Without a visible focus, it’s like using a mouse with an invisible cursor.",
      zh: "很多人用键盘浏览——行动不便的人、读屏软件用户、追求效率的高级用户。没有可见焦点，就像用一个看不见光标的鼠标。",
      ja: "運動機能に障害のある人、スクリーンリーダーの利用者、効率重視のパワーユーザーなど、多くの人がキーボードで操作します。フォーカスが見えないのは、カーソルが見えないマウスを使うようなものです。",
    },
    how: {
      th: [
        "ทุกองค์ประกอบที่โต้ตอบได้ต้องรับโฟกัสได้ และลำดับการกด Tab ต้องสมเหตุสมผล เช่น จากบนลงล่าง ซ้ายไปขวา",
        "กรอบโฟกัสต้องมองเห็นชัด มีคอนทราสต์อย่างน้อย 3:1 และไม่ถูกองค์ประกอบอื่นบัง",
        "CSS :focus-visible แสดงกรอบเฉพาะตอนใช้คีย์บอร์ด จึงไม่รบกวนคนที่ใช้เมาส์ ไม่มีเหตุผลที่จะลบกรอบโฟกัสทิ้งอีกต่อไป",
      ],
      en: [
        "Every interactive element must be focusable, and the Tab order must follow a logical sequence — top to bottom, left to right.",
        "The focus indicator needs to be clearly visible, with at least 3:1 contrast, and never hidden behind other elements.",
        "CSS :focus-visible shows the ring only for keyboard use, so mouse users aren’t bothered — there’s no longer any excuse to remove it.",
      ],
      zh: [
        "每个可交互元素都必须能获得焦点，Tab 键的顺序要合乎逻辑——从上到下、从左到右。",
        "焦点指示必须清晰可见，对比度至少 3:1，并且不能被其他元素遮挡。",
        "CSS 的 :focus-visible 只在使用键盘时显示焦点框，不会打扰鼠标用户——已经没有任何理由去删掉它了。",
      ],
      ja: [
        "操作できる要素はすべてフォーカス可能にし、Tab の順序は上から下、左から右のように論理的に。",
        "フォーカス表示ははっきり見えること。コントラスト比は 3:1 以上、他の要素に隠れないように。",
        "CSS の :focus-visible を使えば、キーボード操作のときだけ枠を表示でき、マウス利用者の邪魔になりません。もう枠を消す理由はありません。",
      ],
    },
    inPractice: {
      th: [
        "กรอบสีรอบปุ่มเมื่อกด Tab ไล่ไปบนเว็บไซต์",
        "ช่องกรอกที่ขอบสว่างขึ้นเมื่อพร้อมให้พิมพ์",
        "ไฮไลต์ที่เลื่อนไปบนเมนูทีวีเมื่อกดรีโมต",
      ],
      en: [
        "Coloured rings around buttons as you Tab through a site",
        "Input fields whose border lights up when ready for typing",
        "TV remotes moving a highlight across on-screen menus",
      ],
      zh: ["用 Tab 键浏览网站时按钮周围出现的彩色框", "可以输入时边框会亮起的输入框", "用电视遥控器在屏幕菜单上移动的高亮框"],
      ja: ["Tab で移動すると、ボタンの周りに表示される色付きの枠", "入力できる状態になると縁が光る入力欄", "テレビのリモコンで画面のメニュー上を動くハイライト"],
    },
    mistake: {
      th: "เขียน outline: none เพราะคิดว่ากรอบโฟกัส “ไม่สวย” ผู้ใช้คีย์บอร์ดจะหลงทางทันที",
      en: "Adding outline: none because focus rings look “ugly”. Keyboard users are instantly lost.",
      zh: "因为觉得焦点框“难看”就写上 outline: none。键盘用户会立刻迷失方向。",
      ja: "フォーカス枠が「かっこ悪い」からと outline: none にすること。キーボード利用者はすぐに迷子になります。",
    },
    takeaway: {
      th: "โฟกัสคือเคอร์เซอร์ของคีย์บอร์ด อย่าลบทิ้ง ออกแบบให้สวยแทน",
      en: "Focus is the keyboard’s cursor. Don’t remove it — design it beautifully.",
      zh: "焦点就是键盘的光标。不要删掉它——把它设计得漂亮。",
      ja: "フォーカスはキーボードのカーソル。消さずに、美しくデザインしよう。",
    },
    related: ["accessibility", "hover", "modal", "tooltip"],
    sources: ["wcag-focus-visible", "wcag-focus-appearance", "wcag-keyboard", "wcag-focus-order"],
    aliases: ["โฟกัส", "focus ring", "focus-visible", "tab", "keyboard", "outline", "フォーカス", "焦点"],
  },
  {
    id: "disabled-state",
    term: "Disabled state",
    ipa: "/dɪˈseɪ.bəld steɪt/",
    localTerm: {
      th: "สถานะปิดใช้งาน",
      en: "Inactive or unavailable state",
      zh: "禁用状态",
      ja: "無効状態（ディセーブル）",
    },
    categories: ["state"],
    difficulty: 2,
    short: {
      th: "หน้าตาขององค์ประกอบที่ยังใช้งานไม่ได้ในตอนนี้ มักจางลงและกดไม่ได้",
      en: "How an element looks when it can’t be used right now — usually faded and unresponsive.",
      zh: "元素当前无法使用时的样子——通常颜色变淡、点击无反应。",
      ja: "いまは使えない要素の見た目。たいてい薄く表示され、押しても反応しません。",
    },
    instruction: {
      th: "ลองกด “ยืนยันการจอง” ทั้งสองแบบ ก่อนจะกรอกข้อมูลให้ครบ แบบไหนบอกคุณว่าต้องทำอะไรต่อ?",
      en: "Try pressing “Confirm booking” in both versions before filling everything in. Which one tells you what to do next?",
      zh: "在两个版本中，都先不填完就试着点击“确认预订”。哪一个告诉了你下一步该做什么？",
      ja: "両方のバージョンで、すべて入力する前に「予約を確定」を押してみましょう。次に何をすべきか教えてくれるのはどちら？",
    },
    demo: "disabled-state",
    problem: {
      th: "บางการกระทำยังทำไม่ได้จนกว่าจะครบเงื่อนไข ผู้ใช้ต้องรู้ทั้งว่า “ทำไม่ได้” และ “ทำไมถึงทำไม่ได้”",
      en: "Some actions aren’t possible until conditions are met. People need to know not just that they can’t — but why, and how to fix it.",
      zh: "有些操作要满足条件后才能进行。人们不仅需要知道“不能”，还需要知道“为什么”以及“怎么解决”。",
      ja: "条件がそろうまで実行できない操作があります。人は「できない」ことだけでなく、「なぜできないのか」「どうすればできるのか」を知る必要があります。",
    },
    how: {
      th: [
        "สถานะปิดใช้งานมักใช้สีจางและไม่ตอบสนองต่อการกด แต่ถ้าไม่มีคำอธิบาย ผู้ใช้จะติดอยู่โดยไม่รู้ว่าต้องทำอะไร",
        "ทางเลือกที่มักดีกว่า: ให้กดได้ แล้วบอกว่ายังขาดอะไร หรือเขียนเงื่อนไขไว้ใกล้ ๆ ปุ่มเลย",
        "ปุ่มที่ปิดใช้งานมักถูกข้ามเมื่อใช้คีย์บอร์ดหรือโปรแกรมอ่านหน้าจอ บางคนจึงไม่รู้ด้วยซ้ำว่ามีปุ่มนี้อยู่",
      ],
      en: [
        "Disabled elements are usually faded and ignore presses — but without an explanation, people get stuck with no idea what to do.",
        "Often better: keep the button active and explain what’s missing when pressed, or state the requirement right next to it.",
        "Disabled buttons are often skipped by keyboards and screen readers, so some people never learn the button exists.",
      ],
      zh: [
        "禁用的元素通常会变淡、对点击没有反应——但如果没有解释，人们就会卡住，不知道该做什么。",
        "通常更好的做法：保持按钮可点，点击时说明还缺什么；或者在按钮旁边直接写明条件。",
        "禁用按钮常常会被键盘和读屏软件跳过，有些人甚至不知道这个按钮的存在。",
      ],
      ja: [
        "無効な要素はたいてい薄く表示され、押しても反応しません。でも説明がないと、人は何をすればいいか分からず行き詰まります。",
        "多くの場合、より良い方法があります。ボタンは押せるままにして、押したときに足りないものを伝えるか、ボタンのそばに条件を書いておくことです。",
        "無効なボタンはキーボードやスクリーンリーダーで飛ばされることが多く、存在に気づかない人もいます。",
      ],
    },
    inPractice: {
      th: [
        "ปุ่ม “ถัดไป” ที่จางอยู่จนกว่าจะเลือกที่นั่งในแอปจองตั๋ว",
        "ปุ่ม “ส่งรหัส OTP อีกครั้ง” ที่กดไม่ได้พร้อมตัวนับถอยหลัง",
        "ไซซ์ที่สินค้าหมด ซึ่งแสดงไว้แต่เลือกไม่ได้",
      ],
      en: [
        "A faded “Next” button until you pick a seat in a ticketing app",
        "“Resend code” disabled with a visible countdown",
        "Out-of-stock sizes shown but unavailable",
      ],
      zh: ["在购票 App 中选好座位前呈灰色的“下一步”按钮", "带倒计时、暂时不能点击的“重新发送验证码”", "显示出来但无法选择的缺货尺码"],
      ja: ["チケットアプリで座席を選ぶまで薄く表示される「次へ」ボタン", "カウントダウン付きで押せない「コードを再送信」", "表示はされるが選べない在庫切れのサイズ"],
    },
    mistake: {
      th: "ปิดปุ่มส่งฟอร์มไว้เฉย ๆ โดยไม่บอกว่ายังขาดข้อมูลช่องไหน ผู้ใช้ต้องไล่หาเองทีละช่อง",
      en: "Disabling the submit button with no hint about which field is missing — people have to hunt field by field.",
      zh: "直接禁用提交按钮，却不提示缺了哪个字段——人们只能一个一个去找。",
      ja: "どの欄が足りないのか示さずに送信ボタンを無効にすること。ユーザーは 1 つずつ探す羽目になります。",
    },
    takeaway: {
      th: "ถ้าจะปิดปุ่ม ให้บอกเหตุผลและทางแก้เสมอ",
      en: "If you disable something, always say why and how to unlock it.",
      zh: "如果要禁用某个东西，一定要说明原因和解锁方法。",
      ja: "何かを無効にするなら、必ず理由と解除の方法を伝える。",
    },
    related: ["button", "error-state", "default-state", "accessibility"],
    sources: ["nng-button-states", "m3-states", "nng-form-errors"],
    aliases: ["ปิดใช้งาน", "disabled", "inactive", "greyed out", "無効", "グレーアウト", "禁用", "置灰"],
  },
  {
    id: "loading-state",
    term: "Loading state",
    ipa: "/ˈləʊ.dɪŋ steɪt/",
    localTerm: {
      th: "สถานะกำลังโหลด",
      en: "Pending or busy state",
      zh: "加载状态",
      ja: "ローディング状態",
    },
    categories: ["state"],
    difficulty: 2,
    short: {
      th: "สิ่งที่หน้าจอแสดงระหว่างรอ เพื่อบอกว่าระบบยังทำงานอยู่ ไม่ได้ค้าง",
      en: "What the screen shows while people wait — proof the system is working, not frozen.",
      zh: "等待时屏幕显示的内容——证明系统正在工作，而不是卡住了。",
      ja: "待っている間に画面が見せるもの。システムが止まっているのではなく、動いている証拠です。",
    },
    instruction: {
      th: "โหลดฟีดข่าวด้วยทั้งสามแบบ: หน้าว่าง Spinner และ Skeleton แบบไหนรู้สึกว่ารอนานที่สุด?",
      en: "Load the news feed three ways: blank, spinner and skeleton. Which wait feels longest?",
      zh: "用三种方式加载新闻流：空白、加载动画和骨架屏。哪一种等待感觉最漫长？",
      ja: "ニュースフィードを 3 通りで読み込んでみましょう。空白、スピナー、スケルトン。いちばん長く感じる待ち時間はどれ？",
    },
    demo: "loading-state",
    problem: {
      th: "เครือข่ายช้าหรือเซิร์ฟเวอร์ประมวลผลนานเป็นเรื่องปกติ ถ้าหน้าจอเงียบ ผู้ใช้จะคิดว่าระบบพัง แล้วกดซ้ำหรือออกไปเลย",
      en: "Slow networks and busy servers are normal. If the screen goes quiet, people assume it broke — and tap again or leave.",
      zh: "网络慢、服务器忙是常态。如果屏幕毫无动静，人们会以为出错了——于是再点一次或直接离开。",
      ja: "ネットワークが遅かったり、サーバーが混んでいたりするのはよくあることです。画面が静まり返ると、人は壊れたと思い、もう一度押すか、去ってしまいます。",
    },
    how: {
      th: [
        "รอ 1–2 วินาที: Spinner หรือปุ่มที่เปลี่ยนเป็น “กำลังส่ง…” ก็เพียงพอ",
        "โหลดทั้งหน้า: Skeleton screen (โครงร่างสีเทาที่มีรูปทรงเหมือนเนื้อหา) ช่วยให้เห็นว่ากำลังจะได้อะไร และทำให้รู้สึกว่ารอสั้นลง",
        "รอนานกว่าราว 10 วินาที: ควรใช้แถบความคืบหน้าที่บอกเปอร์เซ็นต์ และให้ผู้ใช้ยกเลิกได้",
      ],
      en: [
        "A 1–2 second wait: a spinner, or a button that changes to “Sending…”, is enough.",
        "Loading a whole page: a skeleton screen (grey placeholders shaped like the content) previews what’s coming and makes the wait feel shorter.",
        "Over about 10 seconds: show a progress bar with a percentage, and let people cancel.",
      ],
      zh: [
        "等待 1–2 秒：一个加载动画，或按钮变成“发送中…”就足够了。",
        "加载整个页面：骨架屏（形状像内容的灰色占位块）能预告即将出现的内容，让等待感觉更短。",
        "超过约 10 秒：显示带百分比的进度条，并允许取消。",
      ],
      ja: [
        "1〜2 秒の待ち時間なら、スピナーや「送信中…」に変わるボタンで十分です。",
        "ページ全体を読み込むなら、スケルトンスクリーン（コンテンツの形をしたグレーの仮置き）で、何が表示されるかを予告し、待ち時間を短く感じさせます。",
        "約 10 秒を超えるなら、パーセント付きの進捗バーを表示し、キャンセルできるようにします。",
      ],
    },
    inPractice: {
      th: [
        "โครงร่างโพสต์สีเทาในแอปโซเชียลก่อนเนื้อหาจริงจะขึ้น",
        "ปุ่ม “ชำระเงิน” ที่เปลี่ยนเป็น Spinner และกดซ้ำไม่ได้",
        "การดาวน์โหลดไฟล์ที่บอกเวลาที่เหลือ",
      ],
      en: [
        "Grey post outlines in social apps before content appears",
        "A “Pay” button that turns into a spinner and can’t be double-tapped",
        "File downloads that show the time remaining",
      ],
      zh: ["社交 App 中内容出现前的灰色帖子轮廓", "变成加载动画、无法重复点击的“支付”按钮", "显示剩余时间的文件下载进度"],
      ja: ["SNS アプリでコンテンツが出る前に表示されるグレーの投稿の枠", "スピナーに変わり、二重タップできない「支払う」ボタン", "残り時間を表示するファイルのダウンロード"],
    },
    mistake: {
      th: "ใช้ Spinner หมุนไปเรื่อย ๆ โดยไม่บอกอะไรเลยสำหรับงานที่ใช้เวลานาน ผู้ใช้ไม่รู้ว่าควรรอต่อหรือควรยอมแพ้",
      en: "An endless spinner with no information for long tasks — people can’t tell whether to keep waiting or give up.",
      zh: "长时间任务只显示一个没完没了的加载动画、不给任何信息——人们无法判断该继续等还是放弃。",
      ja: "時間のかかる処理で、何の情報もないスピナーを回し続けること。待つべきか、あきらめるべきか分かりません。",
    },
    takeaway: {
      th: "ระหว่างรอ อย่าปล่อยให้หน้าจอเงียบ",
      en: "Never let a wait be silent.",
      zh: "等待时，绝不让屏幕沉默。",
      ja: "待ち時間を、決して無言にしない。",
    },
    related: ["feedback", "success-state", "error-state", "button"],
    sources: ["nng-progress", "nng-skeleton", "nng-response-times", "hig-progress"],
    aliases: ["โหลด", "กำลังโหลด", "loading", "spinner", "skeleton", "progress", "ローディング", "読み込み中", "加载", "骨架屏"],
  },
  {
    id: "error-state",
    term: "Error state",
    ipa: "/ˈer.ə steɪt/",
    localTerm: {
      th: "สถานะข้อผิดพลาด",
      en: "Validation error",
      zh: "错误状态",
      ja: "エラー状態",
    },
    categories: ["state"],
    difficulty: 2,
    short: {
      th: "หน้าตาและข้อความที่บอกผู้ใช้ว่ามีบางอย่างผิดพลาด อยู่ตรงไหน และแก้อย่างไร",
      en: "How the interface shows that something went wrong — where, and how to fix it.",
      zh: "界面如何显示出了问题——在哪里，以及怎么修正。",
      ja: "何かがうまくいかなかったことを、どこで、どう直せばいいかとともに示す見た目と文言。",
    },
    instruction: {
      th: "กรอกเบอร์โทรผิดรูปแบบ (เช่น 12345) แล้วกดส่งทั้งสองแบบ แบบไหนช่วยให้คุณแก้ได้เร็วกว่า?",
      en: "Enter a malformed phone number (like 12345) and submit both versions. Which helps you fix it faster?",
      zh: "输入格式错误的手机号（例如 12345），在两个版本中分别提交。哪一个能让你更快改正？",
      ja: "形式の間違った電話番号（例：12345）を入力して、両方のバージョンで送信してみましょう。早く直せるのはどちら？",
    },
    demo: "error-state",
    problem: {
      th: "ทุกคนทำผิดได้ ปัญหาที่แท้จริงคือข้อความที่ทำให้ผู้ใช้รู้สึกผิด และไม่บอกว่าต้องแก้อย่างไร",
      en: "Everyone makes mistakes. The real problem is error messages that blame people and don’t say how to recover.",
      zh: "每个人都会出错。真正的问题是那些责怪用户、却不说明如何恢复的错误提示。",
      ja: "誰でも間違えます。本当の問題は、人を責めるだけで、どう立て直せばいいかを伝えないエラーメッセージです。",
    },
    how: {
      th: [
        "ข้อความแจ้งข้อผิดพลาดที่ดีต้องอยู่ใกล้จุดที่ผิด บอกว่าผิดอะไรด้วยภาษาคน และบอกวิธีแก้ เช่น “กรอกเบอร์มือถือ 10 หลัก เช่น 081 234 5678”",
        "อย่าใช้สีแดงอย่างเดียว ให้มีไอคอนและข้อความด้วย และเชื่อมข้อความกับช่องด้วย aria-invalid และ aria-describedby เพื่อให้โปรแกรมอ่านหน้าจออ่านออกเสียงได้",
        "ดีที่สุดคือป้องกันไม่ให้ผิดตั้งแต่แรก บอกรูปแบบก่อน รับรูปแบบที่ยืดหยุ่น และห้ามล้างข้อมูลที่ผู้ใช้กรอกไว้แล้ว",
      ],
      en: [
        "A good error message sits right next to the problem, says what went wrong in plain language, and how to fix it: “Enter an 11-digit mobile number, like 07700 900123.”",
        "Don’t rely on red alone — add an icon and text — and connect the message with aria-invalid and aria-describedby so screen readers announce it.",
        "Best of all, prevent the error: state the format up front, accept flexible input, and never wipe what people already typed.",
      ],
      zh: [
        "好的错误提示紧挨着出问题的地方，用平实的语言说明哪里错了，以及如何修正：“请输入 11 位手机号，例如 138 0013 8000。”",
        "不要只用红色——加上图标和文字，并用 aria-invalid 和 aria-describedby 关联提示，让读屏软件能读出来。",
        "最好的办法是预防错误：提前说明格式，接受灵活的输入，并且绝不清空用户已经填写的内容。",
      ],
      ja: [
        "良いエラーメッセージは問題のすぐそばにあり、何が間違っているかを平易な言葉で伝え、直し方を示します。「11 桁の携帯番号を入力してください（例：090 1234 5678）」。",
        "赤色だけに頼らず、アイコンと文字も添えます。aria-invalid と aria-describedby でメッセージを関連付け、スクリーンリーダーが読み上げられるようにします。",
        "いちばん良いのは、エラーを防ぐこと。形式を先に伝え、柔軟な入力を受け付け、すでに入力された内容を決して消さないこと。",
      ],
    },
    inPractice: {
      th: [
        "ข้อความใต้ช่องรหัสผ่านที่บอกว่ายังขาดเงื่อนไขข้อไหน",
        "ฟอร์มที่สรุปข้อผิดพลาดทั้งหมดไว้ด้านบน พร้อมลิงก์ไปยังแต่ละช่อง",
        "หน้า 404 ที่ช่วยพาไปยังหน้าที่ใช้งานได้",
      ],
      en: [
        "Password fields that list which rule is still unmet",
        "Forms with an error summary at the top that links to each field",
        "404 pages that help you find your way",
      ],
      zh: ["列出还有哪条规则未满足的密码框", "顶部汇总所有错误并链接到对应字段的表单", "帮你找到出路的 404 页面"],
      ja: ["どの条件をまだ満たしていないかを示すパスワード欄", "上部にエラーをまとめ、各欄へリンクするフォーム", "行き先を案内してくれる 404 ページ"],
    },
    mistake: {
      th: "แสดงข้อความกว้าง ๆ อย่าง “ข้อมูลไม่ถูกต้อง” ที่ด้านบนของฟอร์มยาว ๆ ผู้ใช้ไม่รู้เลยว่าผิดช่องไหน",
      en: "Showing a vague “Invalid input” at the top of a long form — people can’t tell which field is wrong.",
      zh: "在长表单顶部只显示一句含糊的“输入无效”——人们根本不知道是哪个字段错了。",
      ja: "長いフォームの上部に「入力が正しくありません」とだけ表示すること。どの欄が間違っているのか分かりません。",
    },
    takeaway: {
      th: "บอกว่าผิดตรงไหน ผิดอะไร และแก้อย่างไร โดยไม่โทษผู้ใช้",
      en: "Say where, what and how to fix — without blaming the person.",
      zh: "说清楚在哪里、错在哪、怎么改——而不是责怪用户。",
      ja: "どこで、何が、どう直せばいいかを伝える。人を責めずに。",
    },
    related: ["input-field", "feedback", "success-state", "disabled-state"],
    sources: ["nng-form-errors", "nng-hostile-errors", "govuk-error-message", "govuk-validation", "wcag-error-identification"],
    aliases: ["ข้อผิดพลาด", "แจ้งเตือน", "error", "validation", "エラー", "错误", "报错"],
  },
  {
    id: "success-state",
    term: "Success state",
    ipa: "/səkˈses steɪt/",
    localTerm: {
      th: "สถานะสำเร็จ",
      en: "Confirmation state",
      zh: "成功状态",
      ja: "成功状態",
    },
    categories: ["state"],
    difficulty: 1,
    short: {
      th: "สิ่งที่หน้าจอแสดงเมื่องานเสร็จสมบูรณ์ เพื่อยืนยันผลและบอกว่าทำอะไรต่อได้",
      en: "What the screen shows when a task is complete — confirming the result and what to do next.",
      zh: "任务完成时屏幕显示的内容——确认结果，并告诉你接下来可以做什么。",
      ja: "タスクが完了したときに画面が見せるもの。結果を確かめ、次にできることを伝えます。",
    },
    instruction: {
      th: "ลองโอนเงินจำลองด้วยทั้งสองแบบ แบบไหนทำให้คุณมั่นใจ และรู้ว่าต้องทำอะไรต่อ?",
      en: "Make a pretend transfer with both versions. Which one leaves you confident — and knowing what to do next?",
      zh: "用两个版本分别进行一次模拟转账。哪一个让你更安心，并且知道下一步该做什么？",
      ja: "両方のバージョンで、模擬の振込をしてみましょう。安心できて、次にすることが分かるのはどちら？",
    },
    demo: "success-state",
    problem: {
      th: "หลังทำเรื่องสำคัญ เช่น จ่ายเงินหรือยื่นเอกสาร ผู้ใช้ต้องการหลักฐานว่าสำเร็จจริง และรายละเอียดที่ตรวจสอบหรือเก็บไว้ได้",
      en: "After something important — paying, submitting an application — people want proof it really worked, with details they can check or keep.",
      zh: "完成重要操作后——付款、提交申请——人们希望得到真正成功的证明，以及可以核对或保存的详细信息。",
      ja: "支払いや申請の送信など大切なことをしたあと、人は本当に成功した証拠と、確認・保存できる詳細を求めます。",
    },
    how: {
      th: [
        "ยืนยันให้ชัดว่าสำเร็จด้วยข้อความ ไอคอน และสี (ไม่ใช่สีอย่างเดียว) และประกาศให้โปรแกรมอ่านหน้าจอรับรู้ในรูปแบบ Status message",
        "สรุปสิ่งที่เกิดขึ้น เช่น จำนวนเงิน ผู้รับ เวลา และเลขที่อ้างอิง เพื่อให้ผู้ใช้ตรวจสอบและเก็บไว้เป็นหลักฐานได้",
        "บอกขั้นตอนถัดไป เช่น “บันทึกสลิป” หรือ “กลับหน้าหลัก” สถานะสำเร็จที่ดีไม่ใช่ทางตัน",
      ],
      en: [
        "Confirm clearly with words, an icon and colour (not colour alone), and announce it to screen readers as a status message.",
        "Summarise what happened — amount, recipient, time, reference number — so people can verify it and keep a record.",
        "Offer the next step: “Save receipt” or “Back to home”. A good success state isn’t a dead end.",
      ],
      zh: [
        "用文字、图标和颜色（不只靠颜色）清楚地确认成功，并以状态消息的形式让读屏软件读出来。",
        "总结发生了什么——金额、收款人、时间、参考编号——方便人们核对并留存记录。",
        "提供下一步：“保存凭证”或“返回首页”。好的成功状态不是死胡同。",
      ],
      ja: [
        "言葉、アイコン、色（色だけに頼らない）で成功をはっきり伝え、ステータスメッセージとしてスクリーンリーダーにも知らせます。",
        "金額、受取人、時刻、参照番号など、何が起きたかをまとめ、確認・記録できるようにします。",
        "次のステップを示します。「明細を保存」や「ホームに戻る」。良い成功状態は行き止まりではありません。",
      ],
    },
    inPractice: {
      th: [
        "สลิปโอนเงินพร้อมปุ่มบันทึกรูปในแอปธนาคาร",
        "หน้าขอบคุณหลังสั่งซื้อที่บอกเลขคำสั่งซื้อและเวลาจัดส่ง",
        "เครื่องหมายถูกสีเขียวหลังอัปเดตข้อมูลโปรไฟล์",
      ],
      en: [
        "Transfer slips with a “Save image” button in banking apps",
        "Order confirmation pages with an order number and delivery time",
        "A green checkmark after updating your profile",
      ],
      zh: ["银行 App 中带“保存图片”按钮的转账凭证", "显示订单号和送达时间的下单成功页", "更新个人资料后出现的绿色对勾"],
      ja: ["銀行アプリの「画像を保存」ボタン付きの振込明細", "注文番号とお届け予定を表示する注文完了ページ", "プロフィール更新後に表示される緑のチェックマーク"],
    },
    mistake: {
      th: "แสดงคำว่า “สำเร็จ!” แค่วินาทีเดียวแล้วหายไป ก่อนผู้ใช้จะทันอ่านหรือจดเลขที่อ้างอิง",
      en: "Flashing “Success!” for a second and making it vanish before people can read it or note the reference number.",
      zh: "“成功！”只闪现一秒就消失，人们还没来得及阅读或记下参考编号。",
      ja: "「成功！」を一瞬だけ表示して消してしまい、読んだり参照番号を控えたりする暇を与えないこと。",
    },
    takeaway: {
      th: "สถานะสำเร็จที่ดี = ยืนยัน + หลักฐาน + ทางไปต่อ",
      en: "Good success = confirmation + proof + a next step.",
      zh: "好的成功状态 = 确认 + 凭证 + 下一步。",
      ja: "良い成功状態 ＝ 確認 ＋ 証拠 ＋ 次の一歩。",
    },
    related: ["feedback", "loading-state", "error-state"],
    sources: ["nng-visibility", "wcag-status-messages", "hig-feedback"],
    aliases: ["สำเร็จ", "ยืนยัน", "success", "confirmation", "成功", "完了", "确认"],
  },
];
